/**
 * Urdu glossary — part 3/4 · AI assistant, alerts, authentication, mobile
 * driver/client modes and the registration flow.
 */
export const UR_MOBILE: Record<string, string> = {
  /* AI assistant */
  "EJAZ AI Logistics Assistant": "اعجاز اسسٹنٹ برائے لاجسٹکس",
  "مساعد إيجاز الذكي للوجستيات": "اعجاز اسسٹنٹ برائے لاجسٹکس",
  "Online · Live": "آن لائن · لائیو",
  "Predictive operations, smart dispatching, and dynamic fleet analytics": "پیش گوئی، سمارٹ ڈسپیچ اور فلیٹ تجزیات",
  "Smart Recommendations": "سمارٹ سفارشات",
  "Natural Language Query": "قدرتی زبان میں سوال",
  "Predictive Fleet Health": "فلیٹ کی پیش گوئی صحت",
  "Fleet Utilization Optimization": "فلیٹ استعمال کو بہتر بنائیں",
  "Inspect Truck": "ٹرک دیکھیں",
  "Execute Dispatch": "ڈسپیچ نافذ کریں",
  "Dynamic ETA & Delay Mitigation": "متوقع وقت اور تاخیر کا ازالہ",
  "View Trip on Live Map": "ٹرپ لائیو نقشے پر دیکھیں",
  "Cold Chain Certification": "کولڈ چین سرٹیفکیٹ",
  "Ask in Arabic or English: 'Where are Jeddah trucks?', 'Delayed trips'...": "عربی، انگریزی یا اردو میں پوچھیں: ’تاخیر والے ٹرپس کون سے ہیں؟‘…",
  "Analyzing...": "تجزیہ جاری...",
  "Ask AI": "پوچھیں",
  "Quick Suggested Prompts:": "فوری تجویز کردہ سوالات:",
  "AI Dispatch Intelligence Answer:": "اسسٹنٹ کا جواب:",
  "View Filtered Results in Console": "کنسول میں نتائج دیکھیں",
  "Reefer Actros EZ-10483 temperature stabilized at -18.5°C.": "ریفر ایکٹروس EZ-10483 کا درجہ حرارت ‎-18.5°C پر مستحکم ہے۔",
  "Continuous telemetry streaming verified. Electronic delivery certificate ready for consignee digital signature upon arrival in Riyadh.": "مسلسل ٹیلی میٹری کی تصدیق ہو گئی۔ ریاض پہنچنے پر وصول کنندہ کے ڈیجیٹل دستخط کے لیے الیکٹرانک سرٹیفکیٹ تیار ہے۔",
  "Active Fleet Summary & AI Assessment": "فلیٹ کی مکمل صورتحال اور جائزہ",

  /* Alerts */
  "Smart Telemetry Alerts Center": "سمارٹ ٹیلی میٹری اطلاعات مرکز",
  "Real-time geofencing, temperature drift, speed limits, and highway alerts": "براہِ راست جیو فینسنگ، درجہ حرارت، رفتار کی حد اور شاہراہ اطلاعات",
  "All Alerts": "تمام اطلاعات",
  "Critical": "انتہائی اہم",
  "Warning": "انتباہ",
  "Information": "معلومات",
  "Resolved": "حل شدہ",
  "Inspect Trip": "ٹرپ دیکھیں",
  "Acknowledge & Resolve": "تسلیم اور حل کریں",
  "No active alerts matching filter.": "فلٹر سے مطابقت رکھنے والی کوئی اطلاع نہیں۔",
  "Mark All as Read": "سب کو پڑھا ہوا کریں",
  "Clear All": "سب صاف کریں",

  /* Login / auth */
  "Unified Operations Control Room": "متحد آپریشنل کنٹرول روم",
  "One authoritative backend. Live AVL telematics, the 18-state trip lifecycle, digital POD, financial settlement and a tamper-evident audit trail — all behind strict role-based access control.": "ایک مستند بیک اینڈ: لائیو ٹیلی میٹری، ۱۸ مرحلوں والا ٹرپ سائیکل، ڈیجیٹل POD، مالی تصفیہ اور محفوظ آڈٹ ٹریل — سخت کردار کی اجازتوں کے ساتھ۔",
  "Canonical States": "مرکزی حالتیں",
  "Official Fleet Types": "سرکاری فلیٹ اقسام",
  "Governed Roles": "مقرر کردار",
  "Authorized personnel only. Every sign-in is recorded in the audit log.": "صرف مجاز افراد۔ ہر سائن اِن آڈٹ لاگ میں درج ہوتا ہے۔",
  "Control Room Sign-in": "کنٹرول روم سائن اِن",
  "Instant preview enabled — click below to enter without password.": "فوری پیش نظارہ فعال — بغیر پاس ورڈ داخل ہونے کے لیے نیچے کلک کریں۔",
  "Enter Control Room Directly (No Password)": "بغیر پاس ورڈ کنٹرول روم میں داخل ہوں",
  "1-Click Demo Accounts (Instant Sign-in)": "ایک کلک ڈیمو اکاؤنٹس (فوری سائن اِن)",
  "Instant Entry": "فوری داخلہ",
  "Enter Now →": "ابھی داخل ہوں ←",
  "Open the driver / client mobile app": "ڈرائیور / کلائنٹ موبائل ایپ کھولیں",
  "Or sign in manually with credentials:": "یا اپنی تفصیلات سے دستی سائن اِن کریں:",
  "Work Email": "کام کا ای میل",
  "Authenticating…": "تصدیق جاری…",
  "Sign in to Control Room": "کنٹرول روم میں سائن اِن",
  "Demo Accounts": "ڈیمو اکاؤنٹس",
  "Back to sign in": "سائن اِن پر واپس",
  "Invalid credentials. Tap any demo account below for instant access.": "غلط تفصیلات۔ فوری رسائی کے لیے نیچے کوئی ڈیمو اکاؤنٹ دبائیں۔",
  "Enter your email and password, or pick one of the demo accounts below.": "اپنا ای میل اور پاس ورڈ درج کریں، یا نیچے کوئی ڈیمو اکاؤنٹ منتخب کریں۔",
  "Choose an account to enter (no password)": "داخل ہونے کے لیے اکاؤنٹ منتخب کریں (بغیر پاس ورڈ)",
  "Password": "پاس ورڈ",
  "Username / Email": "صارف نام / ای میل",
  "Username": "صارف نام",
  "Remember me": "مجھے یاد رکھیں",
  "Forgot password?": "پاس ورڈ بھول گئے؟",
  "Verifying credentials…": "تفصیلات کی تصدیق…",
  "Sign In": "سائن اِن",
  "Sign out": "سائن آؤٹ",
  "Signed in as": "بطور سائن اِن",
  "No account yet?": "ابھی اکاؤنٹ نہیں؟",
  "Submit a formal registration request — the administration reviews it, then your account is activated.": "باضابطہ رجسٹریشن درخواست بھیجیں — انتظامیہ جائزہ لے کر اکاؤنٹ فعال کرتی ہے۔",
  "Sign in with another account": "دوسرے اکاؤنٹ سے سائن اِن",
  "EJAZ Enterprise Logistics Platform V1.0-PROD": "اعجاز انٹرپرائز لاجسٹکس پلیٹ فارم V1.0-PROD",
  "Click any account for instant sign-in": "فوری سائن اِن کے لیے کوئی اکاؤنٹ کلک کریں",
  "Selecting an account signs you in immediately without requiring a password.": "اکاؤنٹ منتخب کرنے پر بغیر پاس ورڈ فوری سائن اِن ہو جائیں گے۔",
  "Reset Password": "پاس ورڈ ری سیٹ",
  "EJAZ Enterprise Security": "اعجاز انٹرپرائز سیکیورٹی",
  "To protect enterprise freight and fleet operations data, password resets require verification by the system administrator or your fleet manager.": "ادارتی ڈیٹا کے تحفظ کے لیے پاس ورڈ ری سیٹ کے لیے سسٹم ایڈمن یا فلیٹ مینیجر کی تصدیق درکار ہے۔",
  "Technical Support Desk:": "تکنیکی معاونت ڈیسک:",
  "Please enter your username/email and password": "صارف نام/ای میل اور پاس ورڈ درج کریں",
  "Invalid username or password. Please verify your credentials.": "صارف نام یا پاس ورڈ غلط ہے۔ تفصیلات دوبارہ دیکھیں۔",
  "Authentication failed. Please check server connectivity.": "تصدیق ناکام۔ سرور سے رابطہ دیکھیں۔",
  "Heavy Fleet Tracking & Logistics": "ہیوی فلیٹ ٹریکنگ اور لاجسٹکس",
  "Tap to Continue": "جاری رکھنے کے لیے دبائیں",
  "Tap anywhere to enter application": "ایپ میں داخل ہونے کے لیے کہیں بھی دبائیں",
  "Client": "کلائنٹ",
  "Admin": "ایڈمن",
  "1-Tap Access": "ایک ٹیپ رسائی",
  "Instant Preview (No Password):": "فوری پیش نظارہ (بغیر پاس ورڈ):",

  /* Registration flow */
  "The document exceeds the 12 MB limit": "دستاویز ۱۲ MB کی حد سے بڑی ہے",
  "Please set a password (at least 8 characters)": "کم از کم ۸ حروف کا پاس ورڈ رکھیں",
  "The request is incomplete — the highlighted items are required before it can be sent.": "درخواست نامکمل ہے — نشان زدہ اشیاء لازمی ہیں۔",
  "Could not send the request": "درخواست نہ بھیجی جا سکی",
  "Complete your registration request": "اپنی رجسٹریشن درخواست مکمل کریں",
  "New registration request": "نئی رجسٹریشن درخواست",
  "Creating an account is a request. The administration reviews it, then the account is activated and you are notified.": "اکاؤنٹ بنانا ایک درخواست ہے۔ انتظامیہ جائزہ لیتی ہے، پھر اکاؤنٹ فعال ہوتا ہے اور آپ کو اطلاع دی جاتی ہے۔",
  "Personal, licence and truck data": "ذاتی، لائسنس اور ٹرک کی معلومات",
  "Contact and facility data": "رابطہ اور سہولت کی معلومات",
  "Account password": "اکاؤنٹ پاس ورڈ",
  "At least 8 characters": "کم از کم ۸ حروف",
  "Required documents": "لازمی دستاویزات",
  "PDF or image. The file is stored with your request for the administration to review.": "PDF یا تصویر۔ فائل آپ کی درخواست کے ساتھ انتظامیہ کے جائزے کے لیے محفوظ رہتی ہے۔",
  "Tap to attach": "منسلک کرنے کے لیے دبائیں",
  "Missing items": "غائب اشیاء",
  "Re-send the request for review": "دوبارہ جائزے کے لیے بھیجیں",
  "Send the request": "درخواست بھیجیں",
  "The account is not approved automatically — the administration reviews every request.": "اکاؤنٹ خودکار منظور نہیں ہوتا — انتظامیہ ہر درخواست کا جائزہ لیتی ہے۔",
  "Your request is being processed": "آپ کی درخواست زیرِ کارروائی ہے",
  "Your request needs more information": "آپ کی درخواست کو مزید معلومات درکار ہیں",
  "Your request has been approved": "آپ کی درخواست منظور ہو گئی",
  "Your request was rejected": "آپ کی درخواست مسترد کر دی گئی",
  "Registration request": "رجسٹریشن درخواست",
  "We received your request successfully. It will be reviewed by the administration and you will be notified once the review is complete.": "آپ کی درخواست موصول ہو گئی۔ انتظامیہ جائزہ لے گی اور مکمل ہونے پر آپ کو اطلاع دی جائے گی۔",
  "Please complete the requested items, then re-send.": "مطلوبہ اشیاء مکمل کر کے دوبارہ بھیجیں۔",
  "Your registration request has been approved. You can now use your account and the available services.": "آپ کی رجسٹریشن منظور ہو گئی۔ اب آپ اپنا اکاؤنٹ اور خدمات استعمال کر سکتے ہیں۔",
  "Contact the administration for details.": "تفصیلات کے لیے انتظامیہ سے رابطہ کریں۔",
  "Items requested by the administration": "انتظامیہ کی مطلوبہ اشیاء",
  "Request number": "درخواست نمبر",
  "Customer": "کلائنٹ",
  "Complete the data and re-send": "ڈیٹا مکمل کر کے دوبارہ بھیجیں",
  "No registration request for this account": "اس اکاؤنٹ کے لیے کوئی رجسٹریشن درخواست نہیں",
  "Loading your request…": "آپ کی درخواست لوڈ ہو رہی ہے…",
  "Refresh status": "حالت تازہ کریں",

  /* Forms & dialogs */
  "Dispatch a vehicle to the fleet and start tracking instantly.": "فلیٹ میں گاڑی بھیجیں اور فوری ٹریکنگ شروع کریں۔",
  "Request type": "درخواست کی قسم",
  "Partner": "پارٹنر",
  "Loading address": "لوڈنگ کا پتہ",
  "Unloading address": "اتارنے کا پتہ",
  "Riyadh · Gate 3": "ریاض · گیٹ ۳",
  "Jeddah · Terminal 12": "جدہ · ٹرمینل ۱۲",
  "Create request": "درخواست بنائیں",
  "Truck": "ٹرک",
  "Repair": "مرمت",
  "Report": "رپورٹ",
  "Driver request": "ڈرائیور درخواست",
  "Customer request": "کلائنٹ درخواست",
  "Document synced": "دستاویز ہم آہنگ",
  "Documents refresh automatically every 15 minutes.": "دستاویزات ہر ۱۵ منٹ میں خودکار تازہ ہوتی ہیں۔",
  "Waiting for pickup": "پک اپ کے انتظار میں",
  "Good morning": "صبح بخیر",
  "Good afternoon": "دوپہر بخیر",
  "Good evening": "شام بخیر",
  "No shipments yet.": "ابھی کوئی کھیپ نہیں۔",
  "Live telemetry on": "لائیو ٹیلی میٹری فعال",
  "Live telemetry paused": "لائیو ٹیلی میٹری روکی گئی",
  "Track on Live Map": "لائیو نقشے پر دیکھیں",
  "Trip requested successfully! Sent to Operations for approval.": "ٹرپ کی درخواست بھیج دی گئی! منظوری کے لیے آپریشنز کو بھیجی گئی۔",
  "Connecting call…": "کال منسلک ہو رہی ہے…",
  "Direct call initiated": "کال شروع کر دی گئی",
  "Message operations": "آپریشنز کو پیغام",
};
