/**
 * Urdu glossary — part 2/4 · fleet, vehicle assets, shipments, reports,
 * registration review and the 3D/imagery surfaces.
 */
export const UR_OPS: Record<string, string> = {
  /* Live operations / overview */
  "Logistics Operations & Performance Analytics": "لاجسٹکس آپریشنز اور کارکردگی کا تجزیہ",
  "Data-driven freight metrics, fuel efficiency, ton-kilometer throughput, and driver rankings": "مال کی نقل و حرکت، ایندھن کی کارکردگی، ٹن-کلومیٹر اور ڈرائیور درجہ بندی کے اعداد و شمار",
  "Day": "دن",
  "Week": "ہفتہ",
  "Month": "مہینہ",
  "Year": "سال",
  "Activities": "سرگرمیاں",
  "Search orders": "آرڈر تلاش کریں",
  "Search order, driver, city…": "آرڈر، ڈرائیور یا شہر تلاش کریں…",
  "Status filter": "حالت کا فلٹر",
  "Cargo filter": "کھیپ کا فلٹر",
  "Order ID": "آرڈر نمبر",
  "Cargo Mix": "کھیپ کی ساخت",
  "Tonnage by trailer type": "ٹریلر کی قسم کے مطابق وزن",
  "Cargo tonnage donut chart": "کھیپ وزن کا چارٹ",
  "Total load": "کل لوڈ",
  "Route efficiency": "راستے کی کارکردگی",
  "On plan": "منصوبے پر",
  "Needs attention": "توجہ درکار",
  "Threshold": "حد",
  "Checked": "جانچا گیا",
  "Passed": "منظور",
  "Tracking Delivery": "ترسیل کی ٹریکنگ",
  "Tracking ID": "ٹریکنگ نمبر",
  "Change shipment": "کھیپ تبدیل کریں",
  "Open trip details": "ٹرپ تفصیلات کھولیں",
  "Shipment Statistic": "کھیپ کے اعداد و شمار",
  "Truck load": "ٹرک لوڈ",
  "Change Route": "راستہ تبدیل کریں",
  "Full Trip Details": "مکمل ٹرپ تفصیلات",
  "Active Highway Shipments": "شاہراہ پر فعال کھیپ",
  "Click any trip to focus map & 3D vehicle": "نقشے اور 3D گاڑی کے لیے ٹرپ پر کلک کریں",
  "Loading Google Maps…": "گوگل میپ لوڈ ہو رہا ہے…",
  "Switch to Google Maps": "گوگل میپ پر جائیں",
  "Open in Google Maps": "گوگل میپ میں کھولیں",
  "Corridor": "کوریڈور",
  "Cargo Load": "کھیپ لوڈ",
  "Est. Remaining": "متوقع باقی",
  "Next Station": "اگلا اسٹیشن",
  "Recenter on truck": "ٹرک پر مرکز کریں",
  "Drop pin": "پن لگائیں",
  "Map layers": "نقشے کی تہیں",
  "Zoom in": "زوم اِن",
  "Zoom out": "زوم آؤٹ",
  "Standing": "کھڑا",
  "Arriving in": "پہنچنے میں",
  "Enterprise Shipments Control": "ادارتی کھیپ کنٹرول",
  "Search shipment, trip, customer, plate...": "کھیپ، ٹرپ، کلائنٹ یا پلیٹ تلاش کریں...",
  "Search shipment, driver, plate…": "کھیپ، ڈرائیور یا پلیٹ تلاش کریں…",
  "Try adjusting your search criteria or resetting the 4-type vehicle filters.": "اپنی تلاش بدلیں یا چار اقسام کے فلٹرز دوبارہ ترتیب دیں۔",
  "Shipment Details & 3D": "کھیپ تفصیلات اور 3D",
  "Trip Manager": "ٹرپ مینیجر",
  "Trip": "ٹرپ",
  "Fleet Manager": "فلیٹ مینیجر",
  "Map": "نقشہ",
  "3D Verified Vehicle Model": "تصدیق شدہ 3D گاڑی ماڈل",
  "Pickup & Loading Point": "پک اپ اور لوڈنگ مقام",
  "Departure": "روانگی",
  "Delivery Point & Consignee": "ترسیل مقام اور وصول کنندہ",
  "Est. Arrival": "متوقع آمد",
  "minutes": "منٹ",
  "Shipment & Trip Lifecycle Timeline": "کھیپ اور ٹرپ کے مراحل کی ٹائم لائن",
  "Electronic POD & Consignment Docs": "الیکٹرانک POD اور کھیپ دستاویزات",
  "Digital Bill of Lading, Weight Ticket & Inspection Certificate": "ڈیجیٹل بارنامہ، وزن پرچی اور معائنہ سرٹیفکیٹ",
  "View POD & Documents": "POD اور دستاویزات دیکھیں",
  "Official Electronic Proof of Delivery (POD)": "سرکاری الیکٹرانک ثبوتِ ترسیل (POD)",
  "Consignment ID": "کھیپ نمبر",
  "Approved Vehicle Category": "منظور شدہ گاڑی کی قسم",
  "Security Seal Code": "سیکیورٹی سیل کوڈ",
  "Client Consignment Tracking Portal": "کلائنٹ کھیپ ٹریکنگ پورٹل",
  "Verified Shipper": "تصدیق شدہ ارسال کنندہ",
  "Real-time GPS tracking, electronic proof of delivery, and cargo condition telemetry": "لائیو جی پی ایس ٹریکنگ، الیکٹرانک ثبوتِ ترسیل اور کھیپ کی حالت کی نگرانی",
  "View Consignment QR": "کھیپ کیو آر دیکھیں",
  "Share Live Link": "لائیو لنک شیئر کریں",
  "On Road Live": "لائیو سڑک پر",
  "Progress Covered:": "طے شدہ پیش رفت:",
  "Remaining:": "باقی:",
  "My Active Shipments": "میری فعال کھیپ",
  "Live Cold Chain Sensor": "لائیو کولڈ چین سینسر",
  "Target: -18.0°C": "ہدف: ‎-18.0°C",
  "Ejaz Operations Live Support": "اعجاز آپریشنز لائیو معاونت",
  "Online": "آن لائن",
  "Ejaz Support": "اعجاز معاونت",
  "Welcome! Your consignment is currently on schedule and temperature monitored.": "خوش آمدید! آپ کی کھیپ مقررہ وقت پر ہے اور درجہ حرارت زیرِ نگرانی ہے۔",
  "Inquire about delivery...": "ترسیل کے بارے میں پوچھیں...",
  "Electronic Consignment Waybill QR": "الیکٹرانک بارنامہ کیو آر",
  "Scan using camera to access public live tracking link": "عوامی ٹریکنگ لنک کے لیے کیمرے سے اسکین کریں",
  "Fleet Command & Vehicle Control": "فلیٹ کمانڈ اور گاڑیوں کا کنٹرول",
  "Authorized EJAZ heavy fleet with 4 canonical types & 3D telemetry": "اعجاز کا مجاز بھاری فلیٹ: چار اقسام اور 3D ٹیلی میٹری",
  "Search truck, plate...": "ٹرک یا پلیٹ تلاش کریں...",
  "Search by plate, model or type…": "پلیٹ، ماڈل یا قسم سے تلاش کریں…",
  "Add Vehicle": "گاڑی شامل کریں",
  "Add Heavy Fleet Unit": "بھاری فلیٹ یونٹ شامل کریں",
  "Total Fleet": "کل فلیٹ",
  "On Highway Transit": "شاہراہ پر سفر میں",
  "On Trip": "ٹرپ پر",
  "Upload a photograph for this vehicle": "اس گاڑی کے لیے تصویر اپ لوڈ کریں",
  "Change photo": "تصویر تبدیل کریں",
  "Drop to apply to this vehicle": "اس گاڑی پر لاگو کرنے کے لیے چھوڑیں",
  "Custom Image": "حسبِ ضرورت تصویر",
  "Details & 3D Viewer": "تفصیلات اور 3D ویوَر",
  "Live 3D Preview of Selected Type": "منتخب قسم کا لائیو 3D پیش نظارہ",
  "Approved Vehicle Category (Strictly 4)": "منظور شدہ گاڑی کی قسم (صرف چار)",
  "Official Asset for the selected category": "منتخب قسم کا سرکاری اثاثہ",
  "Official image (3D pending)": "سرکاری تصویر (3D زیرِ التواء)",
  "This exact asset is bound to the category across the app and the console — one upload, every screen.": "یہی اثاثہ پوری ایپ اور کنسول میں اسی قسم سے منسلک ہے — ایک اپ لوڈ، ہر اسکرین پر۔",
  "Manufacturer Brand": "کمپنی برانڈ",
  "Brand": "برانڈ",
  "Model": "ماڈل",
  "Model Year": "ماڈل سال",
  "Max Payload (Tons)": "زیادہ سے زیادہ وزن (ٹن)",
  "Cabin Type": "کیبن کی قسم",
  "Custom Vehicle Photo URL (Optional)": "حسبِ ضرورت گاڑی تصویر لنک (اختیاری)",
  "If left empty, the official reference asset for this category will be used.": "خالی چھوڑنے پر اس قسم کا سرکاری اثاثہ استعمال ہوگا۔",
  "Vehicle added successfully": "گاڑی کامیابی سے شامل ہو گئی",
  "Failed to create vehicle": "گاڑی بنانے میں ناکامی",
  "Driver assigned to vehicle": "ڈرائیور گاڑی پر مقرر ہو گیا",
  "Please provide a vehicle plate number": "گاڑی کا نمبر پلیٹ درج کریں",
  "Image size exceeds the permitted limit": "تصویر کا حجم اجازت سے زیادہ ہے",
  "Photograph updated everywhere": "تصویر ہر جگہ اپ ڈیٹ ہو گئی",
  "Could not publish the photograph": "تصویر شائع نہ ہو سکی",
  "Vehicle photograph published — applied everywhere now": "گاڑی کی تصویر شائع — ہر جگہ لاگو",
  "Official category image published — applied everywhere now": "سرکاری قسم کی تصویر شائع — ہر جگہ لاگو",

  /* Vehicle assets manager */
  "Vehicle Assets (Official Source of Truth)": "گاڑیوں کے اثاثے (سرکاری مرجع)",
  "The Android app and this control room read the same catalogue: one official image and one official 3D model per approved category.": "اینڈرائیڈ ایپ اور یہ کنٹرول روم ایک ہی کیٹلاگ پڑھتے ہیں: ہر منظور شدہ قسم کے لیے ایک سرکاری تصویر اور ایک 3D ماڈل۔",
  "Official images": "سرکاری تصاویر",
  "3D models": "3D ماڈلز",
  "Refresh catalogue": "کیٹلاگ تازہ کریں",
  "Official reference image": "سرکاری حوالہ تصویر",
  "Published": "شائع شدہ",
  "Baseline asset": "بنیادی اثاثہ",
  "Public path": "عوامی راستہ",
  "Original file": "اصل فائل",
  "Published at": "شائع ہونے کا وقت",
  "Replace the official image": "سرکاری تصویر بدلیں",
  "Publish the official image": "سرکاری تصویر شائع کریں",
  "Drop the file here, or use the button above. The uploaded file is preserved byte-for-byte as the original and is used across every screen without alteration.": "فائل یہاں چھوڑیں یا اوپر والا بٹن استعمال کریں۔ اپ لوڈ شدہ فائل اصل کے مطابق محفوظ رہتی ہے اور بغیر تبدیلی ہر اسکرین پر استعمال ہوتی ہے۔",
  "Official 3D model (GLB / glTF)": "سرکاری 3D ماڈل (GLB / glTF)",
  "Interactive 3D": "انٹرایکٹو 3D",
  "Not published": "شائع نہیں ہوا",
  "File": "فائل",
  "Size": "حجم",
  "Scale": "پیمانہ",
  "Heading °": "رخ °",
  "Height offset": "اونچائی کی درستی",
  "Replace the model": "ماڈل بدلیں",
  "Withdraw": "واپس لیں",
  "No GLB/glTF has been published for this category yet. The viewer shows the official reference photograph with a clear label — no simulated 3D is ever presented as real.": "اس قسم کے لیے ابھی کوئی GLB/glTF شائع نہیں ہوا۔ ویوَر واضح لیبل کے ساتھ سرکاری تصویر دکھاتا ہے — نقلی 3D کو کبھی حقیقی نہیں بتایا جاتا۔",
  "Publish the official 3D model": "سرکاری 3D ماڈل شائع کریں",
  "Live asset preview": "لائیو اثاثہ پیش نظارہ",
  "Show image": "تصویر دکھائیں",
  "Show viewer": "ویوَر دکھائیں",
  "This is the exact asset rendered by the Android app and every console screen for this category.": "یہی وہ اثاثہ ہے جو اینڈرائیڈ ایپ اور ہر کنسول اسکرین اس قسم کے لیے دکھاتی ہے۔",
  "Vehicle photographs": "گاڑیوں کی تصاویر",
  "Upload a photograph for any truck in the fleet — it replaces the category image for that unit only and is applied on every screen the moment it is published. Drag a file onto a card, or use its upload button.": "فلیٹ کے کسی بھی ٹرک کی تصویر اپ لوڈ کریں — یہ صرف اسی یونٹ کے لیے ہوتی ہے اور شائع ہوتے ہی ہر اسکرین پر لاگو ہوتی ہے۔",
  "Replace": "بدلیں",
  "Upload": "اپ لوڈ",
  "Remove and restore the official asset": "ہٹا کر سرکاری اثاثہ بحال کریں",
  "How this propagates": "یہ کیسے پھیلتا ہے",
  "Android application (driver & client modes)": "اینڈرائیڈ ایپ (ڈرائیور اور کلائنٹ موڈ)",
  "Fleet registry cards and vehicle details": "فلیٹ رجسٹری کارڈز اور گاڑی تفصیلات",
  "Add vehicle / edit vehicle screens": "گاڑی شامل یا ترمیم اسکرینیں",
  "Trips and shipments wherever the vehicle is shown": "ٹرپس اور کھیپ جہاں گاڑی دکھائی جاتی ہے",
  "Reports and the operational dashboard": "رپورٹس اور آپریشنل ڈیش بورڈ",
  "Approved categories: Flatbed · Refrigerated · Dry Van · Curtainsider — and no fifth type.": "منظور شدہ اقسام: فلیٹ بیڈ · ریفر · ڈرائی وین · کرٹن سائیڈر — پانچویں قسم نہیں۔",
  "3D WebGL Viewport": "3D WebGL ویو پورٹ",
  "Vehicle photograph": "گاڑی کی تصویر",
  "Official category photograph": "سرکاری قسم کی تصویر",
  "View angle": "دیکھنے کا زاویہ",
  "Official image": "سرکاری تصویر",
  "Fleet 3D model": "فلیٹ 3D ماڈل",
  "Reset Camera View (3/4 Front)": "کیمرہ ری سیٹ کریں (سامنے 3/4)",
  "Show the official photograph": "سرکاری تصویر دکھائیں",
  "Toggle 3D / photograph": "3D / تصویر تبدیل کریں",
  "360° Interactive 3D Model · Drag to Rotate": "360° انٹرایکٹو 3D ماڈل · گھمانے کے لیے کھینچیں",
  "Official reference image · tap to open the 3D model": "سرکاری حوالہ تصویر · 3D ماڈل کے لیے دبائیں",
  "Real Fleet Unit": "حقیقی فلیٹ یونٹ",
  "3D 360° · drag to rotate": "3D 360° · گھمانے کے لیے کھینچیں",
  "Photo": "تصویر",
  "Toggle 360° Auto-Rotation": "360° خودکار گردش",
  "Body type": "گاڑی کی قسم",
  "Optimal": "بہترین",
  "Asset": "اثاثہ",
  "Official 3D model": "سرکاری 3D ماڈل",
  "Publish a photograph for this vehicle": "اس گاڑی کے لیے تصویر شائع کریں",
  "official reference asset": "سرکاری حوالہ اثاثہ",
  "Open the interactive 3D view": "انٹرایکٹو 3D منظر کھولیں",
  "Unsupported image format. Use PNG, JPG, WEBP or AVIF.": "تصویر کی قسم قبول نہیں۔ PNG، JPG، WEBP یا AVIF استعمال کریں۔",
  "Only GLB or glTF 2.0 files are accepted.": "صرف GLB یا glTF 2.0 فائلیں قبول ہیں۔",
  "Official 3D model published": "سرکاری 3D ماڈل شائع ہو گیا",
  "Model upload failed": "ماڈل اپ لوڈ ناکام",
  "Could not update the model framing": "ماڈل فریمنگ اپ ڈیٹ نہ ہو سکی",
  "Model withdrawn — the official image is displayed instead": "ماڈل واپس لے لیا گیا — اب سرکاری تصویر دکھائی جاتی ہے",
  "Could not withdraw the model": "ماڈل واپس نہ لیا جا سکا",
  "Vehicle photograph removed — official asset restored": "گاڑی تصویر ہٹا دی گئی — سرکاری اثاثہ بحال",
  "Could not remove the photograph": "تصویر ہٹائی نہ جا سکی",

  /* Branding */
  "Central Branding & Identity Settings": "مرکزی برانڈنگ اور شناخت کی سیٹنگز",
  "Propagates official logo and company branding across Admin, Mobile, Reports and Login": "سرکاری لوگو اور برانڈنگ ایڈمن، موبائل، رپورٹس اور سائن اِن پر لاگو کرتا ہے",
  "Central branding updated successfully and propagated system-wide!": "مرکزی برانڈنگ کامیابی سے اپ ڈیٹ اور پورے نظام پر لاگو ہو گئی!",
  "Official Vector Emblem & Asset": "سرکاری ویکٹر نشان اور اثاثہ",
  "Name (Arabic)": "نام (عربی)",
  "Name (English)": "نام (انگریزی)",
  "Name (Urdu)": "نام (اردو)",
  "Tagline (Arabic)": "سلوگن (عربی)",
  "Tagline (English)": "سلوگن (انگریزی)",
  "Tagline (Urdu)": "سلوگن (اردو)",
  "Upload Logo File": "لوگو فائل اپ لوڈ کریں",
  "Logo Target": "لوگو کا مقام",
  "Master (all surfaces)": "مرکزی (تمام اسکرینیں)",
  "Admin header / sidebar": "ایڈمن ہیڈر / سائیڈ بار",
  "Login & welcome": "سائن اِن اور خوش آمدید",
  "Reports / PDF": "رپورٹس / پی ڈی ایف",
  "Choose & Upload": "منتخب اور اپ لوڈ کریں",
  "PNG / JPG / WEBP / SVG · up to 4MB": "PNG / JPG / WEBP / SVG · زیادہ سے زیادہ 4MB",
  "Custom Logo Asset URL (optional)": "حسبِ ضرورت لوگو لنک (اختیاری)",
  "Primary Orange Accent Color": "بنیادی نارنجی رنگ",
  "Navy Anchor Brand Color": "نیوی رنگ",
  "Save & Propagate Branding": "برانڈنگ محفوظ اور لاگو کریں",

  /* Dispatch chat / archive / reports */
  "Dispatch & Highway Communications": "ڈسپیچ اور شاہراہ مواصلات",
  "Real-time tactical communication channel between Operations dispatchers and highway captains": "آپریشنز ڈسپیچرز اور ڈرائیوروں کے درمیان براہِ راست رابطہ چینل",
  "Live Radio & Telemetry Link Active": "لائیو ریڈیو اور ٹیلی میٹری لنک فعال",
  "Filter trip channels...": "ٹرپ چینل فلٹر کریں...",
  "Dispatch": "ڈسپیچ",
  "Encrypted dispatch session opened for Trip": "ٹرپ کے لیے محفوظ ڈسپیچ سیشن کھل گیا",
  "Automated Waypoint Alert": "خودکار راستہ اطلاع",
  "Quick Directives": "فوری ہدایات",
  "Direct directive sent": "ہدایت بھیج دی گئی",
  "Send Directive": "ہدایت بھیجیں",
  "Select a trip channel to open dispatch communication": "ڈسپیچ کے لیے ٹرپ چینل منتخب کریں",
  "Fleet control · EJAZ Transport": "فلیٹ کنٹرول · اعجاز ٹرانسپورٹ",
  "Chats": "پیغامات",
  "Driver channels · replies under 2 minutes": "ڈرائیور چینلز · دو منٹ میں جواب",
  "Opened thread": "گفتگو کھل گئی",
  "Filtered by partner": "پارٹنر کے مطابق فلٹر",
  "History": "تاریخ",
  "Last 24 hours of fleet events": "پچھلے ۲۴ گھنٹے کے واقعات",
  "Repair & Maintenance": "مرمت اور دیکھ بھال",
  "Service request sent": "سروس درخواست بھیج دی گئی",
  "Workshop · Riyadh Yard": "ورکشاپ · ریاض یارڈ",
  "Schedule": "شیڈول",
  "Cargo photo reports from the field": "میدان سے کھیپ کی تصویری رپورٹس",
  "Report exported": "رپورٹ برآمد ہو گئی",
  "Trip Archive & Operational Audit Log": "ٹرپ آرکائیو اور آپریشنل آڈٹ لاگ",
  "Permanent ledger of delivered shipments, POD confirmations, and security audit records": "ڈیلیور شدہ کھیپ، POD تصدیقوں اور سیکیورٹی ریکارڈ کا مستقل لیجر",
  "Audit trail exported successfully": "آڈٹ ٹریل برآمد ہو گئی",
  "Delivered Trips Archive": "ڈیلیور شدہ ٹرپس آرکائیو",
  "Security & Operational Audit Log": "سیکیورٹی اور آپریشنل آڈٹ لاگ",
  "Filter archive or audit trail...": "آرکائیو یا آڈٹ ٹریل فلٹر کریں...",
  "No archived trips found matching your criteria": "آپ کے معیار سے کوئی آرکائیو ٹرپ نہیں ملا",
  "Captain / Driver": "کپتان / ڈرائیور",
  "System Audit Trail & Security Ledger": "سسٹم آڈٹ ٹریل اور سیکیورٹی لیجر",
  "End-to-end trip execution: dispatch, GPS milestone tracking, e-waybill, and consignee POD signature": "مکمل ٹرپ عمل: ڈسپیچ، جی پی ایس سنگِ میل، ای بارنامہ اور وصول کنندہ کے دستخط",
  "Active Fleet Consignments": "فلیٹ کی فعال کھیپ",
  "Live On Route": "راستے میں براہِ راست",

  /* Registration review */
  "Driver and customer registration requests awaiting an administrative decision.": "ڈرائیور اور کلائنٹ کی رجسٹریشن درخواستیں انتظامی فیصلے کے منتظر۔",
  "Pending review": "جائزے کے منتظر",
  "Needs completion": "تکمیل درکار",
  "Approved": "منظور",
  "Rejected": "مسترد",
  "Search by number, name, plate or company…": "نمبر، نام، پلیٹ یا کمپنی سے تلاش کریں…",
  "No registration requests": "کوئی رجسٹریشن درخواست نہیں",
  "Select a request to review its data and documents": "ڈیٹا اور دستاویزات دیکھنے کے لیے درخواست منتخب کریں",
  "Driver registration request": "ڈرائیور رجسٹریشن درخواست",
  "Customer registration request": "کلائنٹ رجسٹریشن درخواست",
  "Decision": "فیصلہ",
  "Created": "تخلیق",
  "Linked": "منسلک",
  "Documents and files": "دستاویزات اور فائلیں",
  "No documents attached": "کوئی دستاویز منسلک نہیں",
  "Administrative decision": "انتظامی فیصلہ",
  "Notes / reason (mandatory for rejection)": "نوٹس / وجہ (مسترد کرنے کے لیے لازمی)",
  "e.g. The attached documents are incomplete": "مثلاً: منسلک دستاویزات نامکمل ہیں",
  "Items the applicant must complete": "درخواست دہندہ کو مکمل کرنے والی چیزیں",
  "Approving…": "منظور کیا جا رہا ہے…",
  "Approve": "منظور کریں",
  "Request completion": "تکمیل طلب کریں",
  "Rejecting…": "مسترد کیا جا رہا ہے…",
  "Reject": "مسترد کریں",
  "Review audit trail": "آڈٹ ٹریل دیکھیں",
  "By": "بذریعہ",
  "Requested items": "مطلوبہ اشیاء",
  "No decisions yet": "ابھی کوئی فیصلہ نہیں",
  "Could not open the document": "دستاویز نہ کھل سکی",
  "Could not open the request": "درخواست نہ کھل سکی",
  "Rejection requires a reason": "مسترد کرنے کے لیے وجہ لازمی ہے",
  "Specify the missing data or documents": "غائب ڈیٹا یا دستاویزات بتائیں",
  "Decision failed": "فیصلہ ناکام",
  "Submitted": "جمع شدہ",
  "Reviewed by": "جائزہ لینے والا",
  "Account approved and activated": "اکاؤنٹ منظور اور فعال",
  "Completion requested from the applicant": "درخواست دہندہ سے تکمیل طلب",
  "Request rejected": "درخواست مسترد",
  "Account": "اکاؤنٹ",
};

/**
 * Part 2b — residual strings reported by `node scripts/i18n-audit.mjs`.
 * Kept in the same part so the audit reads 100% coverage for static strings.
 */
Object.assign(UR_OPS, {
  "km/h": "کلومیٹر/گھنٹہ",
  "hp": "ہارس پاور",
  "SAR": "ریال",
  "trips": "ٹرپس",
  "English": "English",
  "Trucks": "ٹرکس",
  "Upload failed": "اپ لوڈ ناکام",
  "mi left": "میل باقی",
  "mi": "میل",
  "In transit": "راستے میں",
  "PDF · pending": "پی ڈی ایف · زیرِ التواء",
  "Filter by Brand": "برانڈ کے مطابق فلٹر",
  "Filter by Partners": "پارٹنرز کے مطابق فلٹر",
  "Message dispatched to driver": "پیغام ڈرائیور کو بھیج دیا گیا",
  "Engine Temp": "انجن کا درجہ حرارت",
  "All Crew": "تمام عملہ",
  "Search by driver name, phone, license...": "نام، فون یا لائسنس سے تلاش کریں...",
  "No drivers found matching your search": "تلاش سے کوئی ڈرائیور نہیں ملا",
  "Try clearing your search query or adjusting filters": "تلاش صاف کریں یا فلٹر بدلیں",
  "Assign Driver to Vehicle": "گاڑی پر ڈرائیور مقرر کریں",
  "Select Fleet Driver": "فلیٹ ڈرائیور منتخب کریں",
  "Select driver...": "ڈرائیور منتخب کریں...",
  "Assign": "مقرر کریں",
  "Interactive 3D Engine · Drag 360°": "انٹرایکٹو 3D انجن · 360° گھمائیں",
  "Active Visual Asset": "فعال بصری اثاثہ",
  "Custom Vehicle Photo": "گاڑی کی حسبِ ضرورت تصویر",
  "Official Type Asset": "سرکاری قسم کا اثاثہ",
  "Reverted to official type image": "سرکاری قسم کی تصویر بحال کر دی گئی",
  "Use Official Image": "سرکاری تصویر استعمال کریں",
  "Currently bound to official category asset. Single source of truth across Web and Android.":
    "اس وقت سرکاری قسم کے اثاثے سے منسلک ہے۔ ویب اور اینڈرائیڈ کے لیے واحد مرجع۔",
  "The published photograph is used for this unit only; its category asset still governs the fleet type.":
    "شائع شدہ تصویر صرف اسی یونٹ کے لیے ہے؛ فلیٹ قسم کے لیے سرکاری اثاثہ ہی مستند رہتا ہے۔",
  "Override with Custom Photo URL": "حسبِ ضرورت تصویر لنک سے تبدیل کریں",
  "Vehicle image updated": "گاڑی کی تصویر اپ ڈیٹ ہو گئی",
  "Change Vehicle Category (Strictly 4 Types)": "گاڑی کی قسم تبدیل کریں (صرف چار اقسام)",
  "Selecting a category instantly syncs both the official image and the 3D model across all screens.":
    "قسم منتخب کرنے پر سرکاری تصویر اور 3D ماڈل تمام اسکرینوں پر فوری ہم آہنگ ہو جاتے ہیں۔",
  "Category updated": "قسم اپ ڈیٹ ہو گئی",
  "Horsepower": "ہارس پاور",
  "Fuel Level": "ایندھن کی سطح",
  "EJAZ Heavy Fleet Asset Management System": "اعجاز ہیوی فلیٹ اثاثہ جات نظام",
  "Cargo Photo Reports": "کھیپ کی تصویری رپورٹس",
  "Add photo": "تصویر شامل کریں",
  "Search Trip, Shipment, Truck, Driver...": "ٹرپ، کھیپ، ٹرک یا ڈرائیور تلاش کریں...",
  "No matching results found for": "کوئی نتیجہ نہیں ملا برائے",
  "Vehicles & Fleet": "گاڑیاں اور فلیٹ",
  "Maps Dev Adapter · Live GPS": "میپ ڈیو اڈاپٹر · لائیو جی پی ایس",
  "km left": "کلومیٹر باقی",
  "Recenter on Truck": "ٹرک پر مرکز کریں",
  "Toggle 3D Operational Stage Scene": "3D آپریشنل منظر تبدیل کریں",
  "Toggle Layer: Vector / Google / Satellite": "تہہ تبدیل کریں: ویکٹر / گوگل / سیٹلائٹ",
  "Next Waypoint:": "اگلا اسٹاپ:",
  "Heading:": "رخ:",
  "EJAZ LIVE OPERATIONS CENTER": "اعجاز لائیو آپریشنز سینٹر",
  "Highway Fleet Telemetry & Central Dispatch": "شاہراہ فلیٹ ٹیلی میٹری اور مرکزی ڈسپیچ",
  "Alerts": "اطلاعات",
  "Satellite": "سیٹلائٹ",
  "Logistics": "لاجسٹکس",
  "Center on Selected Truck": "منتخب ٹرک پر مرکز کریں",
  "GPS Speed": "جی پی ایس رفتار",
  "Remaining": "باقی",
  "Fleet Asset Owner & Investor Dashboard": "فلیٹ مالک اور سرمایہ کار ڈیش بورڈ",
  "Heavy Assets": "بھاری اثاثے",
  "Capital efficiency, fleet maintenance schedules, revenue per kilometer, and asset lifecycle":
    "سرمائے کی کارکردگی، مرمت کے شیڈول، فی کلومیٹر آمدنی اور اثاثوں کا دورانیہ",
  "Units Generating Revenue": "آمدنی دینے والے یونٹس",
  "Est. Monthly Fleet Revenue": "متوقع ماہانہ فلیٹ آمدنی",
  "vs last month": "پچھلے ماہ کے مقابلے",
  "Total Logged Mileage": "کل درج شدہ میل",
  "Across 14 Prime Movers": "۱۴ پرائم موورز پر",
  "Fleet Utilization Rate": "فلیٹ استعمال کی شرح",
  "Target: 85%": "ہدف: ۸۵٪",
  "Maintenance Compliance": "مرمت کی پابندی",
  "Zero safety violations": "حفاظتی خلاف ورزی صفر",
  "Commercial Heavy Vehicles Portfolio": "تجارتی بھاری گاڑیوں کا پورٹ فولیو",
  "Real Mercedes-Benz, Volvo, Scania, and MAN prime movers in service":
    "مرسڈیز بینز، وولوو، اسکانیا اور MAN کے حقیقی پرائم موورز",
  "Registered Trucks": "رجسٹرڈ ٹرکس",
  "Truck & Model": "ٹرک اور ماڈل",
  "Plate & Cab": "پلیٹ اور کیبن",
  "Body Type": "گاڑی کی قسم",
  "Engine Power": "انجن پاور",
  "Operating Status": "آپریٹنگ حالت",
  "In Terminal": "ٹرمینل میں",
  "Workshop Idle": "ورکشاپ میں فارغ",
  "Assigned Vehicle & Fleet Drivers": "مقرر گاڑی اور فلیٹ ڈرائیورز",
  "Sign inside the box to confirm cargo receipt without damage":
    "بغیر نقصان کے وصولی کی تصدیق کے لیے خانے میں دستخط کریں",
  "Draw your signature using mouse or finger touch": "ماؤس یا انگلی سے اپنے دستخط بنائیں",
  "across 6 brands": "چھ برانڈز میں",
  "live telemetry": "لائیو ٹیلی میٹری",
  "yard & paperwork": "یارڈ اور کاغذی کارروائی",
  "Fleet utilisation": "فلیٹ کا استعمال",
  "payload average": "اوسط وزن",
  "Latest activity": "تازہ ترین سرگرمی",
  "EJAZ": "اعجاز",
});

/**
 * Urdu glossary — part 5/5 · console, mobile and dialog strings added by the
 * header/account/settings/notification refactor. Kept in the same
 * "english": "urdu",  line shape the coverage audit reads.
 */
Object.assign(UR_OPS, {
  "licence valid to": "لائسنس معتبر تا",
  "registration & inspection valid": "رجسٹریشن اور معائنہ معتبر",
  "R J D 4821": "آر جے ڈی 4821",
  "Fahd Al-Shamri": "فہد الشمری",
  "Majed Al-Balawi": "ماجد البلوی",
  "Recipient e-signature": "وصول کنندہ کے دستخط",
  "Flatbed": "فلیٹ بیڈ",
  "Official logo": "سرکاری لوگو",
  "Toggle password visibility": "پاس ورڈ دکھائیں یا چھپائیں",
  "Call driver": "ڈرائیور کو کال کریں",
  "Message driver": "ڈرائیور کو پیغام بھیجیں",
  "https://… or leave empty to use the official type image": "https://… یا خالی چھوڑیں تاکہ قسم کی سرکاری تصویر استعمال ہو",
  "No preview": "کوئی پیش نظارہ نہیں",
  "Previous": "پچھلا",
  "Next": "اگلا",
  "Map layer": "نقشے کی تہہ",
  "Licence": "لائسنس",
  "Driving licence valid & verified": "ڈرائیونگ لائسنس معتبر اور تصدیق شدہ",
  "Additional driver": "اضافی ڈرائیور",
  "Registration, inspection & insurance valid": "رجسٹریشن، معائنہ اور انشورنس معتبر",
  "Consignee & destination data": "وصول کنندہ اور منزل کی تفصیل",
  "Delivery point": "ترسیل کا مقام",
  "Truck & trailer type": "ٹرک اور ٹریلر کی قسم",
  "Net laden weight": "خالص لدا وزن",
  "Estimated distance": "تخمینی فاصلہ",
  "Transport Authority electronic verification token": "ٹرانسپورٹ اتھارٹی کا الیکٹرانک تصدیقی کوڈ",
  "Consignment valid & registered on Bayan": "کھیپ معتبر اور بیان پلیٹ فارم پر درج",
  "Signature": "دستخط",
  "Replace the official trip driver": "ٹرپ کا سرکاری ڈرائیور تبدیل کریں",
  "Driver being unassigned": "ہٹایا جانے والا ڈرائیور",
  "New driver assigned to the trip": "ٹرپ پر مقرر نیا ڈرائیور",
  "Salem Al-Marri": "سالم المری",
  "Abdullah Al-Dosari": "عبداللہ الدوسری",
  "Yousef Al-Otaibi": "یوسف العتیبی",
  "Reason for the swap (mandatory for audit):": "تبدیلی کی وجہ (آڈٹ کے لیے لازمی):",
  "Reason for the swap (mandatory for audit)": "تبدیلی کی وجہ (آڈٹ کے لیے لازمی)",
  "State the justified field reason for the swap…": "تبدیلی کی میدانی اور جائز وجہ لکھیں…",
  "Cancel": "منسوخ",
  "Confirm the swap & record it": "تبدیلی کی تصدیق اور ریکارڈ درج کریں",
  "Replace the approved trip vehicle": "ٹرپ کی منظور شدہ گاڑی تبدیل کریں",
  "Vehicle being released": "فارغ کی جانے والی گاڑی",
  "Curtain": "پردہ",
  "Approved replacement vehicle (the 4 official types only)": "منظور شدہ متبادل گاڑی (صرف چار سرکاری اقسام)",
  "B R D 9104": "بی آر ڈی 9104",
  "Reefer": "ریفریجریٹر",
  "S T H 5520": "ایس ٹی ایچ 5520",
  "J A F 7714": "جے اے ایف 7714",
  "Dry box": "خشک باکس",
  "S T H 8319": "ایس ٹی ایچ 8319",
  "Justified reason for the swap (audit):": "تبدیلی کی جائز وجہ (آڈٹ):",
  "Justified reason for the swap (audit)": "تبدیلی کی جائز وجہ (آڈٹ)",
  "Reason for the vehicle swap and the GPS device update…": "گاڑی کی تبدیلی اور جی پی ایس ڈیوائس اپ ڈیٹ کی وجہ…",
  "Confirm the vehicle swap & update tracking": "گاڑی کی تبدیلی کی تصدیق اور ٹریکنگ اپ ڈیٹ",
  "EJAZ Transport truck": "اعجاز ٹرانسپورٹ کا ٹرک",
  "All (4 classes)": "تمام (چار اقسام)",
  "Reset view": "منظر ری سیٹ کریں",
  "Document": "دستاویز",
  "Request document": "درخواست کی دستاویز",
  "certified by the Transport Authority": "ٹرانسپورٹ اتھارٹی سے تصدیق شدہ",
  "Tarek Mansour (SADAFCO)": "طارق منصور (سدافکو)",
  "On duty": "ڈیوٹی پر",
  "Accuracy": "درستگی",
  "Last ping": "آخری سگنل",
  "Official recipient name": "وصول کنندہ کا سرکاری نام",
  "e.g. Tarek Mansour": "مثلاً طارق منصور",
  "Recipient phone number": "وصول کنندہ کا فون نمبر",
  "Cargo condition notes": "سامان کی حالت کے نوٹس",
  "Certified with a digital fingerprint": "ڈیجیٹل فنگر پرنٹ سے تصدیق شدہ",
  "Approved licence number": "منظور شدہ لائسنس نمبر",
  "heavy transport": "بھاری نقل و حمل",
  "Driving licence validity": "ڈرائیونگ لائسنس کی مدت",
  "Valid until": "معتبر تا",
  "Operational rating": "آپریشنل ریٹنگ",
  "184 completed trips": "184 مکمل ٹرپس",
  "Mercedes-Benz Actros from the EJAZ Transport fleet": "اعجاز ٹرانسپورٹ فلیٹ کی مرسڈیز بینز ایکٹروس",
  "Sign in": "سائن اِن",
  "The EJAZ assistant escalated an alert": "اعجاز اسسٹنٹ نے الرٹ کو تصدیق سے آگے بڑھایا",
  "Fleet vehicles": "فلیٹ کی گاڑیاں",
  "All cargo": "تمام کارگو",
  "Refrigerated": "ریفریجریٹڈ",
  "Dry van": "ڈرائی وین",
  "Curtainsider": "پردے والی ٹریلر گاڑی",
  "No trips to display": "دکھانے کے لیے کوئی ٹرپ نہیں",
  "Trips will appear here when available to your account.": "ٹرپس آپ کے اکاؤنٹ کے لیے دستیاب ہونے پر یہاں دکھائی دیں گے۔",
  "Operations overview · EJAZ Transport Establishment": "آپریشنز کا جائزہ · اعجاز ٹرانسپورٹ اسٹیبلشمنٹ",
  "Search trips, customers, drivers…": "ٹرپ، گاہک یا ڈرائیور تلاش کریں…",
  "Checking GPS…": "جی پی ایس کی جانچ جاری ہے…",
  "GPS provider connected": "جی پی ایس فراہم کنندہ منسلک ہے",
  "Tracking not configured": "ٹریکنگ ترتیب نہیں دی گئی",
  "GPS status unavailable": "جی پی ایس کی حالت دستیاب نہیں",
  "Operations summary": "آپریشنز کا خلاصہ",
  "Trips in view": "نظر آنے والے ٹرپس",
  "Current filters": "موجودہ فلٹرز",
  "Trips currently underway": "اس وقت جاری ٹرپس",
  "Registered vehicles": "رجسٹرڈ گاڑیاں",
  "Fleet inventory": "فلیٹ کی فہرست",
  "Open Fleet from the navigation menu.": "نیویگیشن مینیو سے فلیٹ کھولیں۔",
  "Available driver records": "دستیاب ڈرائیور ریکارڈز",
  "Driver records": "ڈرائیور ریکارڈز",
  "Open Drivers from the navigation menu.": "نیویگیشن مینیو سے ڈرائیورز کھولیں۔",
  "EJAZ fleet truck": "اعجاز فلیٹ کا ٹرک",
  "Selected trip": "منتخب ٹرپ",
  "Route progress": "راستے کی پیش رفت",
  "Distance remaining": "باقی فاصلہ",
  "Trip details": "ٹرپ کی تفصیلات",
  "Operations & fleet snapshot": "آپریشنز اور فلیٹ کا خلاصہ",
  "Counts are calculated from the records currently available to you.": "اعداد و شمار اس وقت آپ کے لیے دستیاب ریکارڈز سے شمار کیے گئے ہیں۔",
  "Cargo type filters": "کارگو کی قسم کے فلٹرز",
  "Select a trip to inspect its assigned vehicle and approved cargo type.": "مقررہ گاڑی اور منظور شدہ کارگو کی قسم دیکھنے کے لیے ٹرپ منتخب کریں۔",
  "vehicles": "گاڑیاں",
  "No vehicles match these filters.": "ان فلٹرز سے کوئی گاڑی مطابقت نہیں رکھتی۔",
  "Trips & activity": "ٹرپس اور سرگرمی",
  "matching records": "مطابقت رکھنے والے ریکارڈز",
  "Provider configured; live positions are shown only when a device feed is available.": "فراہم کنندہ ترتیب دیا گیا ہے؛ براہ راست مقامات صرف ڈیوائس فیڈ دستیاب ہونے پر دکھائے جاتے ہیں۔",
  "Live locations unavailable until a GPS provider is configured.": "جی پی ایس فراہم کنندہ ترتیب دینے تک براہ راست مقامات دستیاب نہیں ہیں۔",
  "Trip status": "ٹرپ کی حالت",
  "All statuses": "تمام حالتیں",
  "All customers": "تمام گاہک",
  "All drivers": "تمام ڈرائیورز",
  "Checking GPS configuration": "جی پی ایس کی ترتیب کی جانچ جاری ہے",
  "Live vehicle positions will appear after the provider status is verified.": "فراہم کنندہ کی تصدیق کے بعد گاڑیوں کے براہ راست مقامات دکھائے جائیں گے۔",
  "GPS service is not configured": "جی پی ایس سروس ترتیب نہیں دی گئی",
  "Live tracking is unavailable. Configure a real GPS provider and link vehicle devices to view verified locations.": "براہ راست ٹریکنگ دستیاب نہیں۔ تصدیق شدہ مقامات کے لیے حقیقی جی پی ایس فراہم کنندہ ترتیب دیں اور گاڑیوں کے آلات منسلک کریں۔",
  "No simulated locations are displayed.": "نقلی مقامات نہیں دکھائے جا رہے۔",
  "Select a trip to focus its verified vehicle feed.": "تصدیق شدہ گاڑی فیڈ دیکھنے کے لیے ٹرپ منتخب کریں۔",
  "Select a trip to open its operational details.": "آپریشنل تفصیلات کھولنے کے لیے ٹرپ منتخب کریں۔",
  "Trips and shipments": "ٹرپس اور ترسیلات",
  "Truck load capacity": "ٹرک کی گنجائش",
  "of load": "لوڈ کا",
  "Cargo temperature": "کارگو کا درجۂ حرارت",
  "Vehicle status": "گاڑی کی حالت",
  "Maintenance & repairs": "مرمت اور دیکھ بھال",
  "Speed unavailable without GPS": "جی پی ایس کے بغیر رفتار دستیاب نہیں",
  "Engine temperature": "انجن کا درجۂ حرارت",
  "EJAZ truck types": "اعجاز ٹرک کی اقسام",
  "Four approved types · select one to filter trips and focus its assigned truck.": "چار منظور شدہ اقسام · ٹرپس فلٹر کرنے اور متعلقہ گاڑی دیکھنے کے لیے ایک قسم منتخب کریں۔",
  "approved types": "منظور شدہ اقسام",
});
