/**
 * Urdu strings for the organised app surfaces (§5-§16): mobile app settings,
 * user management forms, driver/client apps, the settings center and the
 * sign-in preview. Consumed by `ur.glossary.ts` alongside the shell/ops/mobile
 * maps so an Urdu session never shows English or Arabic UI copy.
 */
export const UR_ORGANIZATION: Record<string, string> = {
  /* ── Account & settings ─────────────────────────────────────────── */
  "Account data": "اکاؤنٹ ڈیٹا",
  "Account type": "اکاؤنٹ کی قسم",
  "Account status": "اکاؤنٹ کی حالت",
  "Account data, security and sessions": "اکاؤنٹ ڈیٹا، سیکیورٹی اور سیشنز",
  "Security & sessions": "سیکیورٹی اور سیشنز",
  "Encrypted session token": "خفیہ سیشن ٹوکن",
  "Signed in with an encrypted session token": "خفیہ سیشن ٹوکن کے ذریعے لاگ ان",
  "Every sign-in is recorded in the audit log": "ہر لاگ ان آڈٹ لاگ میں درج ہوتا ہے",
  "Under review": "زیرِ نظرثانی",
  "Active": "فعال",
  "Phone": "فون",
  "My account": "میرا اکاؤنٹ",
  "Settings": "سیٹنگز",
  "Settings & support": "سیٹنگز اور معاونت",
  "Sign out": "سائن آؤٹ",
  "Tap again to confirm": "تصدیق کے لیے دوبارہ دبائیں",
  "Personal information of the signed-in user": "لاگ ان صارف کی ذاتی معلومات",
  "Notifications": "اطلاعات",
  "No notifications yet.": "ابھی تک کوئی اطلاع نہیں۔",
  "Refresh": "تازہ کریں",
  "Loading…": "لوڈ ہو رہا ہے…",
  "Back": "واپس",
  "Current": "موجودہ",

  /* ── App settings ───────────────────────────────────────────────── */
  "App Settings": "ایپ سیٹنگز",
  "App settings": "ایپ سیٹنگز",
  "Language, appearance, time & date": "زبان، ظاہری شکل، وقت اور تاریخ",
  "Choose the interface language": "انٹرفیس کی زبان منتخب کریں",
  "Light · Dark · System": "لائٹ · ڈارک · سسٹم",
  "System": "سسٹم کے مطابق",
  "Follow the device colour scheme": "ڈیوائس کے رنگی نظام کی پیروی کریں",
  "Active theme": "فعال تھیم",
  "Time & date": "وقت اور تاریخ",
  "Clock and date display preferences": "گھڑی اور تاریخ دکھانے کی ترجیحات",
  "Time format": "وقت کا فارمیٹ",
  "24-hour or 12-hour clock": "۲۴ گھنٹے یا ۱۲ گھنٹے کی گھڑی",
  "Date format": "تاریخ کا فارمیٹ",
  "Gregorian display preference": "عیسوی تاریخ دکھانے کی ترجیح",
  "Preview": "معاينة",
  "App information": "ایپ کی معلومات",
  "Platform, establishment and system": "پلیٹ فارم، ادارہ اور نظام",
  "Platform": "پلیٹ فارم",
  "App version": "ایپ ورژن",
  "EJAZ Transport Establishment": "مؤسسة اعجاز ٹرانسپورٹ",
  "Unified fleet & logistics platform": "موحد فلیٹ اور لاجسٹکس پلیٹ فارم",
  "System environment": "سسٹم ماحول",
  "Production": "پروڈکشن",
  "Interface type": "انٹرفیس کی قسم",
  "Choose the interface authorized for your account": "اپنے اکاؤنٹ کے لیے مجاز انٹرفیس منتخب کریں",
  "Driver app": "ڈرائیور ایپ",
  "Client app": "کلائنٹ ایپ",

  /* ── Mobile apps & preview ──────────────────────────────────────── */
  "Mobile apps": "موبائل ایپس",
  "Trips, tracking, documents and account": "ٹرپس، ٹریکنگ، دستاویزات اور اکاؤنٹ",
  "Dispatch, trips, GPS and account": "ڈسپیچ، ٹرپس، GPS اور اکاؤنٹ",
  "Both apps run on the same backend, database, accounts and permissions — every action reflects across the whole system.":
    "دونوں ایپس ایک ہی بیک اینڈ، ڈیٹابیس، اکاؤنٹس اور اجازتوں پر چلتی ہیں — ہر عمل پورے نظام میں ظاہر ہوتا ہے۔",
  "Preview only": "معاينة فقط",
  "Preview mode — sign-in is disabled.": "وضع المعاينة — تسجيل الدخول معطّل.",
  "Sign-in screen preview": "سائن اِن اسکرین کی معاينة",
  "Preview only — sign-in and app entry are disabled.": "معاينة فقط — سائن اِن اور ایپ داخلہ معطل ہیں۔",
  "Shows exactly what an unauthenticated visitor sees. No control-room, driver-app or client-app entry buttons are included inside the preview.":
    "بالکل وہی دکھاتا ہے جو ایک غیر مصدقہ وزیٹر دیکھتا ہے۔ معاينة کے اندر کنٹرول روم، ڈرائیور ایپ یا کلائنٹ ایپ کے کوئی داخلہ بٹن نہیں ہیں۔",
  "Open the client app": "کلائنٹ ایپ کھولیں",
  "Open the driver app": "ڈرائیور ایپ کھولیں",

  /* ── System settings ────────────────────────────────────────────── */
  "Establishment identity": "ادارے کی شناخت",
  "Name, logos, contact data": "نام، لوگوز، رابطے کا ڈیٹا",
  "Users & staff": "صارفین اور عملہ",
  "Driver registry & licences": "ڈرائیور رجسٹری اور لائسنس",
  "Customers & merchants accounts": "کلائنٹس اور تاجروں کے اکاؤنٹس",
  "Registration requests & approvals": "رجسٹریشن کی درخواستیں اور منظوریاں",
  "Staff & admin accounts": "عملہ اور ایڈمن اکاؤنٹس",
  "Roles & permissions (RBAC)": "کردار اور اجازتیں (RBAC)",
  "Role": "کردار",
  "Create driver": "ڈرائیور شامل کریں",
  "Create customer": "کلائنٹ شامل کریں",
  "Review": "نظرثانی",
  "Enforced in the API on every call — hiding a button is never the protection.":
    "ہر کال پر API میں نافذ — بٹن چھپانا کبھی حفاظت نہیں ہے۔",
  "Example": "مثال",
  "Draft → Pending → Confirmed → Loading → In transit → Arrived → Delivered → Settled":
    "مسودة → معلق → مؤكدة → تحميل → في الطريق → وصلت → سُلّمت → مُسوّاة",
  "Numbers come only from the backend generator; cancellations, reopening and archiving follow the canonical state machine.":
    "نمبر صرف بیک اینڈ جنریٹر سے آتے ہیں؛ منسوخی، دوبارہ کھولنا اور آرکائو مقررہ اسٹیٹ مشین کی پیروی کرتے ہیں۔",
  "Four official body types + assets": "چار سرکاری باڈی اقسام + اثاثے",
  "Provider active": "فراہم کنندہ فعال",
  "Checking provider…": "فراہم کنندہ چیک ہو رہا ہے…",
  "GPS service is not configured": "GPS سروس ترتیب شدہ نہیں ہے",
  "Ledger, invoices & settlements": "کھاتہ، بل اور تسویے",
  "Waybills, PODs & permits": "وے بل، POD اور اجازت نامے",
  "PDF · Excel · Print": "PDF · Excel · پرنٹ",
  "Sensitive operations record": "حساس عملیات کا ریکارڈ",

  /* ── Driver app ─────────────────────────────────────────────────── */
  "Driver app ": "ڈرائیور ایپ ",
  "Welcome": "خوش آمدید",
  "On duty": "ڈیوٹی پر",
  "Assigned Vehicle:": "تخصیص شدہ گاڑی:",
  "Current trip": "موجودہ ٹرپ",
  "Open current trip": "موجودہ ٹرپ کھولیں",
  "No trips are assigned to you yet.": "ابھی تک آپ کو کوئی ٹرپ تخصیص نہیں ہوا۔",
  "Browse available trips": "دستیاب ٹرپس براؤز کریں",
  "Trips & Available Dispatch": "ٹرپس اور دستیاب ڈسپیچ",
  "All": "تمام",
  "Available": "دستیاب",
  "Confirmed": "مؤكدة",
  "In progress": "جاری",
  "Completed": "مکمل",
  "No trips in this list.": "اس فہرست میں کوئی ٹرپ نہیں۔",
  "No available trips right now.": "اس وقت کوئی ٹرپ دستیاب نہیں۔",
  "Accept trip": "ٹرپ قبول کریں",
  "Open": "کھولیں",
  "Trip number": "ٹرپ نمبر",
  "Route": "راستہ",
  "Status": "حالت",
  "Start trip (IN_TRANSIT)": "ٹرپ شروع کریں (IN_TRANSIT)",
  "Arrived at destination": "منزل پر پہنچ گئی",
  "Proof of delivery (POD)": "تسلیمی کا ثبوت (POD)",
  "No current trip selected.": "کوئی موجودہ ٹرپ منتخب نہیں۔",
  "Unable to send the trip request right now.": "اس وقت ٹرپ کی درخواست بھیجنا ممکن نہیں۔",
  "Unable to update the trip status.": "ٹرپ کی حالت تازہ کرنا ممکن نہیں۔",
  "Recipient name": "وصول کنندہ کا نام",
  "Recipient phone": "وصول کنندہ کا فون",
  "Delivery notes": "تسلیمی نوٹس",
  "The recipient signed digitally": "وصول کنندہ نے ڈیجیٹل طور پر دستخط کیے",
  "Recording…": "ریکارڈ ہو رہا ہے…",
  "Confirm delivery (POD)": "تسلیمی کی تصدیق (POD)",
  "Enter the recipient name and confirm the signature.": "وصول کنندہ کا نام درج کریں اور دستخط کی تصدیق کریں۔",
  "Confirm the recipient's digital signature first.": "پہلے وصول کنندہ کے ڈیجیٹل دستخط کی تصدیق کریں۔",
  "Proof of delivery recorded and the trip is closed.": "تسلیمی کا ثبوت ریکارڈ ہو گیا اور ٹرپ بند ہو گئی۔",
  "Start GPS": "GPS شروع کریں",
  "Stop GPS": "GPS روکیں",
  "No active trip": "کوئی فعال ٹرپ نہیں",
  "Latitude": "عرض البلد",
  "Longitude": "طول البلد",
  "Speed": "رفتار",
  "GPS service is not configured on the platform. Device GPS broadcasting still works; live fleet telemetry requires the provider setup.":
    "پلیٹ فارم پر GPS سروس ترتیب شدہ نہیں۔ ڈیوائس GPS نشریہ ابھی بھی کام کرتا ہے؛ براہ راست فلیٹ ٹیلی میٹری کے لیے فراہم کنندہ کی ترتیب درکار ہے۔",

  /* ── Client app ─────────────────────────────────────────────────── */
  "Client app ": "کلائنٹ ایپ ",
  "Active Trips": "فعال ٹرپس",
  "Search by trip number or city…": "ٹرپ نمبر یا شہر سے تلاش کریں…",
  "Request a trip": "ٹرپ کی درخواست کریں",
  "Please complete the required shipment fields.": "براہِ کرم درکار شپمنٹ فیلڈز مکمل کریں۔",
  "Trip request created — number": "ٹرپ کی درخواست بن گئی — نمبر",
  "status: awaiting operations review": "حالت: آپریشنز نظرثانی کا انتظار",
  "Submit trip request": "ٹرپ کی درخواست جمع کریں",
  "Submitting…": "جمع ہو رہا ہے…",
  "Origin city": "شہرِ مبدا",
  "Destination city": "شہرِ منزل",
  "Pickup address": "پک اپ پتہ",
  "Delivery address": "تسلیمی کا پتہ",
  "Cargo description": "مال کی تفصیل",
  "Weight (tons)": "وزن (ٹن)",
  "Truck body type": "ٹرک باڈی کی قسم",
  "From (Loading)": "نقطۂ لوڈنگ",
  "To (Delivery)": "نقطۂ تسلیم",
  "Cargo:": "مال:",
  "Track Live Location Now": "ابھی براہ راست مقام تلاش کریں",
  "My Shipments": "میری شپمنٹس",
  "View All": "سب دیکھیں",
  "My trips": "میرے ٹرپس",
  "My Trips": "میرے ٹرپس",
  "Tracking": "ٹریکنگ",
  "No trips yet.": "ابھی تک کوئی ٹرپ نہیں۔",
  "Trips": "ٹرپس",
  "Driver:": "ڈرائیور:",
  "Driver not assigned": "ڈرائیور تخصیص نہیں",
  "Documents": "دستاویزات",
  "Open Tracking": "ٹریکنگ کھولیں",
  "Shipment Tracking": "شپمنٹ ٹریکنگ",
  "GPS service is not configured on the platform. Live vehicle telemetry will appear here once the GPS provider is set up.":
    "پلیٹ فارم پر GPS سروس ترتیب شدہ نہیں۔ GPS فراہم کنندہ ترتیب ہوتے ہی گاڑی کی براہ راست ٹیلی میٹری یہاں ظاہر ہوگی۔",
  "Select a trip to track.": "ٹریکنگ کے لیے ٹرپ منتخب کریں۔",
  "Vehicle & Plate:": "گاڑی اور پلیٹ:",
  "Telemetry Status:": "ٹیلی میٹری حالت:",
  "GPS Telemetry Online": "GPS ٹیلی میٹری آن لائن",
  "Shipment Documents & POD": "شپمنٹ دستاویزات اور POD",
  "Official documentation for trip": "ٹرپ کی سرکاری دستاویزات",
  "Electronic Waybill (BOL)": "الیکٹرانک وے بل (BOL)",
  "Not published yet": "ابھی تک شائع نہیں",
  "Proof of Delivery (POD)": "تسلیمی کا ثبوت (POD)",
  "Delivery confirmed": "تسلیمی کی تصدیق ہو گئی",
  "Recipient": "وصول کنندہ",
  "Recorded": "ریکارڈ شدہ",
  "Awaiting delivery confirmation": "تسلیمی کی تصدیق کا انتظار",
  "The driver records the POD at handover": "ڈرائیور ہینڈ اوور پر POD ریکارڈ کرتا ہے",
  "Contact support": "سپورٹ سے رابطہ",
  "Operations desk": "آپریشنز ڈیسک",

  /* ── User management & forms ────────────────────────────────────── */
  "User management": "صارف کا انتظام",
  "Available because your account holds the required permissions": "دستیاب ہے کیونکہ آپ کے اکاؤنٹ کے پاس درکار اجازتیں ہیں",
  "Add new driver": "نیا ڈرائیور شامل کریں",
  "Add new customer": "نیا کلائنٹ شامل کریں",
  "Sends the request to the control room for review": "درخواست نظرثانی کے لیے کنٹرول روم بھیجی جاتی ہے",
  "Unable to load the form. Check the connection.": "فارم لوڈ نہیں ہو سکا۔ کنکشن چیک کریں۔",
  "Please complete the required fields.": "براہِ کرم درکار فیلڈز مکمل کریں۔",
  "Account password must be at least 8 characters.": "اکاؤنٹ پاس ورڈ کم از کم ۸ حروف کا ہونا چاہیے۔",
  "Passwords do not match.": "پاس ورڈ مماثل نہیں ہیں۔",
  "The request was submitted — status: processing. It is now in the control room for review.":
    "درخواست جمع ہو گئی — حالت: زیرِ عمل۔ یہ اب نظرثانی کے لیے کنٹرول روم میں ہے۔",
  "Unable to submit the request.": "درخواست جمع نہیں ہو سکی۔",
  "Select…": "منتخب کریں…",
  "Account password (8+ characters)": "اکاؤنٹ پاس ورڈ (۸+ حروف)",
  "Confirm password": "پاس ورڈ کی تصدیق",
  "Attached": "منسلک",
  "Attach": "منسلک کریں",
  "Missing documents": "غائب دستاویزات",
  "Submit driver request": "ڈرائیور درخواست جمع کریں",
  "Submit customer request": "کلائنٹ درخواست جمع کریں",

  /* Reports & analytics (§25) + honest GPS labels (§24) */
  "Reports & analytics": "رپورٹیں و تجزیات",
  "Real operational & financial data from the enterprise backend": "حقیقی آپریشنل و مالی ڈیٹا مرکزی بیک اینڈ سے",
  "Print": "پرنٹ",
  "Month (YYYY-MM)": "مہینہ (YYYY-MM)",
  "Min revenue (SAR)": "کم از کم آمدنی (ریال)",
  "Loading real report data…": "حقیقی رپورٹ ڈیٹا لوڈ ہو رہا ہے…",
  "Trips (filtered)": "سفر (فلٹر شدہ)",
  "Gross revenue (SAR)": "مجموعی آمدنی (ریال)",
  "Expenses (SAR)": "اخراجات (ریال)",
  "Payments (SAR)": "ادائیگیاں (ریال)",
  "Total trips": "کل سفر",
  "Utilization": "استعمال کی شرح",
  "Revenue": "آمدنی",
  "Expenses": "اخراجات",
  "No trips match the selected filters.": "منتخب فلٹرز سے مطابقت رکھنے والا کوئی سفر نہیں۔",
  "Report generated from live data": "رپورٹ براہ راست ڈیٹا سے تیار کی گئی",
  "Maps Dev Adapter · route preview": "نقشہ ایڈاپٹر · راستے کا پیش منظر",
  "GPS service is not configured — vehicle positions shown are route demos, not live GPS.":
    "GPS سروس ترتیب شدہ نہیں — ظاہر کردہ گاڑیوں کی پوزیشنیں راستے کی مظاہرے ہیں، حقیقی GPS نہیں۔",
  "Speed (route demo)": "رفتار (مظاہرہ)",
  "Route demo moving · not live GPS": "راستے کا مظاہرہ متحرک · حقیقی GPS نہیں",
  "Route demo paused": "راستے کا مظاہرہ روک دیا گیا",
  "Pause demo": "مظاہرہ روکیں",
  "Resume demo": "مظاہرہ جاری کریں",
  "Vehicle": "گاڑی",
  "Payments": "ادائیگیاں",
  "Unable to reach the reporting service.": "رپورٹنگ سروس تک رسائی ممکن نہیں۔",
  /* ── Roles & permissions administration (RBAC) ──────────────────── */
  "Roles & permissions": "کردار اور اختیارات",
  "Control exactly which sections, pages and functions each role sees. Changes apply on save — no code edit.":
    "طے کریں کہ ہر کردار کون سے سیکشن، صفحات اور افعال دیکھ سکتا ہے۔ تبدیلیاں محفوظ کرتے ہی لاگو ہو جاتی ہیں — کوڈ میں ترمیم کے بغیر۔",
  "Loading the permission registry…": "اختیارات کا رجسٹر لوڈ ہو رہا ہے…",
  "Unable to load the permission registry.": "اختیارات کا رجسٹر لوڈ نہیں ہو سکا۔",
  "Retry": "دوبارہ کوشش کریں",
  "Roles": "کردار",
  "edited": "ترمیم شدہ",
  "The system administrator holds full access and cannot be restricted — otherwise nobody could restore access. Edit any other role to control what it sees.":
    "سسٹم ایڈمنسٹریٹر کے پاس مکمل رسائی ہے اور اسے محدود نہیں کیا جا سکتا — ورنہ کوئی بھی رسائی بحال نہ کر سکے گا۔ کسی دوسرے کردار کو ترتیب دیں۔",
  "Search a page or function…": "صفحہ یا فعل تلاش کریں…",
  "granted": "دیے گئے",
  "Restore defaults": "طے شدہ بحال کریں",
  "Save permissions": "اختیارات محفوظ کریں",
  "Saving…": "محفوظ ہو رہا ہے…",
  "Permissions saved": "اختیارات محفوظ ہو گئے",
  "Permissions saved for": "اختیارات محفوظ ہو گئے برائے",
  "added": "شامل",
  "removed": "ہٹائے گئے",
  "Saving failed.": "محفوظ کرنے میں ناکامی۔",
  "Default permissions restored.": "طے شدہ اختیارات بحال ہو گئے۔",
  "Reset failed.": "بحالی ناکام۔",
  "pages": "صفحات",
  "Whole section": "پورا سیکشن",
  "Permission change log": "اختیارات کی تبدیلی کا لاگ",
  "Who changed which role, from what to what, and when.": "کس نے کس کردار کو، کس سے کیا، اور کب تبدیل کیا۔",
  "No permission changes recorded yet.": "ابھی تک اختیارات میں کوئی تبدیلی درج نہیں ہوئی۔",
  "restored defaults": "طے شدہ بحال",
  "updated": "تبدیل شدہ",
  "Show or hide any section, page or function for any role — applied on save.":
    "کسی بھی کردار کے لیے کوئی بھی سیکشن، صفحہ یا فعل دکھائیں یا چھپائیں — محفوظ کرتے ہی لاگو۔",
  "The system administrator holds full access and cannot be restricted":
    "سسٹم ایڈمنسٹریٹر کے پاس مکمل رسائی ہے اور اسے محدود نہیں کیا جا سکتا",

  /* ── Customer, Driver & Vehicle Management ───────────────────────── */
  "VAT Number": "ٹیکس نمبر (VAT)",
  "Save Changes": "تبدیلیاں محفوظ کریں",
  "Deleting…": "حذف ہو رہا ہے…",
  "Confirm Delete": "حذف کرنے کی تصدیق کریں",
  "Missing required fields": "ضروری معلومات غائب ہیں",
  "Contact Person": "رابطہ کار شخص",
  "Email": "ای میل",
  "CR Number": "کمرشل رجسٹریشن نمبر",
  "Phone Number": "فون نمبر",
  "Please enter company name and phone": "براہ کرم کمپنی کا نام اور فون نمبر درج کریں",
  "Customer added successfully": "گاہک کامیابی سے شامل کر دیا گیا",
  "Failed to add customer": "گاہک شامل کرنے میں ناکامی",
  "Customer updated successfully": "گاہک کا ڈیٹا کامیابی سے اپ ڈیٹ ہو گیا",
  "Failed to update customer": "گاہک کی معلومات اپ ڈیٹ کرنے میں ناکامی",
  "Customer removed successfully": "گاہک کامیابی سے ہٹا دیا گیا",
  "Cannot delete customer": "گاہک کو حذف نہیں کیا جا سکتا",
  "Copied to clipboard": "کلپ بورڈ پر کاپی ہو گیا",
  "Customer Directory & Client Accounts": "گاہکوں کی ڈائرکٹری اور کلائنٹ اکاؤنٹس",
  "Authoritative registry of corporate shippers, commercial registrations, VAT certificates & contracts":
    "کارپوریٹ شپرز، کمرشل رجسٹریشنز، ٹیکس سرٹیفکیٹس اور معاہدوں کا مستند رجسٹر",
  "Search by customer, CR, VAT, city...": "گاہک، رجسٹریشن، ٹیکس نمبر یا شہر سے تلاش کریں...",
  "Add Customer": "گاہک شامل کریں",
  "All Cities": "تمام شہر",
  "Active Accounts": "فعال اکاؤنٹس",
  "Active Corridors": "فعال راہداریاں",
  "Loading customer registry…": "گاہکوں کا رجسٹر لوڈ ہو رہا ہے…",
  "No customers found": "کوئی گاہک نہیں ملا",
  "Adjust search query or add a new corporate customer manually":
    "تلاش کی شرائط تبدیل کریں یا نیا کارپوریٹ گاہک دستی طور پر شامل کریں",
  "Add Customer Now": "ابھی گاہک شامل کریں",
  "Click to copy CR": "رجسٹریشن نمبر کاپی کرنے کے لیے کلک کریں",
  "Click to copy VAT": "ٹیکس نمبر کاپی کرنے کے لیے کلک کریں",
  "active trips": "فعال ٹرپس",
  "Ready for orders": "آرڈرز کے لیے تیار",
  "Create shipment for this customer": "اس گاہک کے لیے شپمنٹ بنائیں",
  "New Order": "نیا آرڈر",
  "Add New Corporate Customer": "نیا کارپوریٹ گاہک شامل کریں",
  "Creates approved client account and commercial profile":
    "منظور شدہ کلائنٹ اکاؤنٹ اور تجارتی پروفائل بناتا ہے",
  "Company / Organization Name": "کمپنی / ادارے کا نام",
  "Authorized Contact Person": "مجاز رابطہ کار شخص",
  "Contact Phone": "رابطہ فون نمبر",
  "Commercial Registration (CR)": "کمرشل رجسٹریشن (CR)",
  "Email Address": "ای میل ایڈریس",
  "Physical Address / Warehouse": "حقیقی پتہ / گودام",
  "Portal Password (for client mobile app)": "پورٹل پاس ورڈ (کلائنٹ موبائل ایپ کے لیے)",
  "Confirm & Create Customer": "گاہک کی تصدیق اور تخلیق",
  "Edit Customer Details": "گاہک کی تفصیلات میں ترمیم کریں",
  "Company Name": "کمپنی کا نام",
  "Address": "پتہ",
  "Delete Customer Account": "گاہک کا اکاؤنٹ حذف کریں",
  "Are you sure you want to delete this customer account? This will remove the record from active directories.":
    "کیا آپ واقعی اس گاہک کا اکاؤنٹ حذف کرنا چاہتے ہیں؟ یہ ریکارڈ کو فعال ڈائرکٹریوں سے ہٹا دے گا۔",
  "Please fill all mandatory driver fields": "براہ کرم ڈرائیور کے تمام لازمی خانے پر کریں",
  "Driver added successfully": "ڈرائیور کامیابی سے شامل کر دیا گیا",
  "Failed to add driver": "ڈرائیور شامل کرنے میں ناکامی",
  "Driver updated successfully": "ڈرائیور کی معلومات اپ ڈیٹ ہو گئیں",
  "Failed to update driver": "ڈرائیور کی معلومات اپ ڈیٹ کرنے میں ناکامی",
  "Driver removed successfully": "ڈرائیور کو کامیابی سے ہٹا دیا گیا",
  "Cannot delete driver": "ڈرائیور کو حذف نہیں کیا جا سکتا",
  "Add Driver": "ڈرائیور شامل کریں",
  "Edit Driver Profile": "ڈرائیور پروفائل میں ترمیم کریں",
  "Add Fleet Captain / Driver": "فلیٹ کیپٹن / ڈرائیور شامل کریں",
  "Driver Full Name": "ڈرائیور کا پورا نام",
  "Heavy Driving License No.": "ہیوی ڈرائیونگ لائسنس نمبر",
  "Initial Operational Status": "ابتدائی آپریشنل حیثیت",
  "Mandatory Rest": "لازمی آرام",
  "On Leave": "چھٹی پر",
  "Assign Heavy Truck (Optional)": "ہیوی ٹرک تفویض کریں (اختیاری)",
  "None / Unassigned": "کوئی نہیں / غیر تفویض شدہ",
  "Mobile App Password": "موبائل ایپ پاس ورڈ",
  "Adding…": "شامل کیا جا رہا ہے…",
  "Confirm & Save Driver": "ڈرائیور کی تصدیق اور محفوظ کریں",
  "Edit Driver Data": "ڈرائیور کے ڈیٹا میں ترمیم کریں",
  "Delete Driver Account": "ڈرائیور کا اکاؤنٹ حذف کریں",
  "Are you sure you want to remove this driver from the fleet? This will release any assigned vehicle.":
    "کیا آپ واقعی اس ڈرائیور کو فلیٹ سے ہٹانا چاہتے ہیں؟ یہ تفویض شدہ گاڑی کو آزاد کر دے گا۔",
  "Failed to assign driver": "ڈرائیور تفویض کرنے میں ناکامی",
  "Vehicle updated successfully": "گاڑی کامیابی سے اپ ڈیٹ ہو گئی",
  "Failed to update vehicle": "گاڑی اپ ڈیٹ کرنے میں ناکامی",
  "Vehicle removed successfully": "گاڑی کو کامیابی سے ہٹا دیا گیا",
  "Cannot delete vehicle": "گاڑی کو حذف نہیں کیا جا سکتا",
  "Edit Specs": "تفصیلات میں ترمیم کریں",
  "Delete Vehicle": "گاڑی حذف کریں",
  "Edit Vehicle Data": "گاڑی کے ڈیٹا میں ترمیم کریں",
  "Manufacturer": "تیار کنندہ (برانڈ)",
  "Model Name": "ماڈل کا نام",
  "Operational Status": "آپریشنل حیثیت",
  "Active / On Road": "فعال / سڑک پر",
  "Retire Vehicle from Fleet": "گاڑی کو فلیٹ سے ریٹائر کریں",
  "Are you sure you want to delete this vehicle from active fleet registries? This will disassociate any assigned drivers.":
    "کیا آپ واقعی اس گاڑی کو فعال فلیٹ رجسٹر سے حذف کرنا چاہتے ہیں؟ یہ تمام تفویض شدہ ڈرائیوروں کا تعلق ختم کر دے گا۔",
  "Uploaded images must be in SVG format (.svg).": "اپ لوڈ کی گئی تصاویر کا SVG فارمیٹ (.svg) میں ہونا ضروری ہے۔",
  "Uploaded images must be in SVG format (.svg)": "اپ لوڈ کی گئی تصاویر کا SVG فارمیٹ (.svg) میں ہونا ضروری ہے",
  "SVG Vector Only · scalable without pixelation": "صرف SVG ویکٹر · بغیر پکسلیشن کے قابل توسیع",
  "Failed to load permissions": "اجازتوں کا ریکارڈ لوڈ نہ ہو سکا",
  "Module access level change": "ماڈیول رسائی کی سطح میں تبدیلی",
  "Module access level updated": "ماڈیول رسائی کی سطح اپڈیٹ ہو گئی",
  "Could not update module level": "ماڈیول کی سطح اپڈیٹ نہ ہو سکی",
  "Could not save permissions": "اجازتیں محفوظ نہ ہو سکیں",
  "Reset to factory defaults": "ڈیفالٹ ترتیبات پر بحالی",
  "Role restored to default": "کردار کی ڈیفالٹ اجازتیں بحال ہو گئیں",
  "Reset failed": "ڈیفالٹ بحال نہ ہو سکا",
  "Role enabled": "کردار فعال کر دیا گیا",
  "Role disabled": "کردار غیر فعال کر دیا گیا",
  "Action failed": "کردار کی حالت تبدیل نہ ہو سکی",
  "Custom role deleted": "مخصوص کردار حذف کر دیا گیا",
  "Cannot delete role": "کردار حذف نہ ہو سکا",
  "Role created": "نیا کردار کامیابی سے بن گیا",
  "Could not create role": "کردار نہ بن سکا",
  "Role cloned": "کردار اور اس کی اجازتیں کاپی ہو گئیں",
  "Could not clone role": "کردار کاپی نہ ہو سکا",
  "User permissions saved": "صارف کی اجازتیں محفوظ ہو گئیں",
  "Failed to save user overrides": "صارف کی اجازتیں محفوظ نہ ہو سکیں",
  "User reset to role defaults": "صارف کو کردار کی ڈیفالٹ اجازتوں پر بحال کر دیا گیا",
  "Temporary permission granted": "عارضی اجازت کامیابی سے دے دی گئی",
  "Could not grant temporary permission": "عارضی اجازت نہ دی جا سکی",
  "Temporary permission revoked": "عارضی اجازت منسوخ کر دی گئی",
  "Revocation failed": "منسوخی ناکام رہی",
  "Permission enabled globally": "اجازت پورے نظام میں فعال کر دی گئی",
  "Permission disabled globally": "اجازت پورے نظام میں غیر فعال کر دی گئی",
  "Toggle failed": "اجازت کی حالت تبدیل نہ ہو سکی",
  "Central Dynamic Permission & Role System (EJAZ RBAC)": "مرکزی متحرک اجازت اور کردار کا نظام",
  "NO PERMISSION = NO VISIBILITY + NO API": "بلا اجازت = نہ ظہور + نہ رسائی",
  "Control roles, multi-level permission matrix, data scope (OWN / ASSIGNED / BRANCH / REGION / ALL), individual user Allow/Deny overrides, temporary grants, and full audit logs.": "کرداروں، کثیر سطحی اجازتوں، ڈیٹا کے دائرہ کار، صارفین کی انفرادی اجازتوں اور آڈٹ لاگ پر مکمل کنٹرول۔",
  "Roles & Permission Matrix": "کردار اور اجازتوں کا جدول",
  "Individual User Overrides (Allow / Deny)": "صارفین کی انفرادی اجازتیں",
  "Temporary Grants & Global Switch": "عارضی اجازتیں اور عمومی کنٹرول",
  "Permission Audit Log": "اجازتوں کا آڈٹ لاگ",
  "System & Custom Roles": "بنیادی اور مخصوص کردار",
  "New Role": "نیا کردار",
  "Core": "بنیادی",
  "Custom": "مخصوص",
  "Disabled": "غیر فعال",
  "Modified": "تبدیل شدہ",
  "Full": "مکمل",
  "permissions": "اجازتیں",
  "Role Disabled": "یہ کردار اس وقت غیر فعال ہے",
  "Visible pages:": "نظر آنے والے صفحات:",
  "Granted actions:": "اجازت یافتہ افعال:",
  "Assigned Users": "منسلک صارفین",
  "Data Scope (§8):": "ڈیٹا کا دائرہ کار:",
  "Clone Role": "کردار کاپی کریں",
  "Disable Role": "کردار غیر فعال کریں",
  "Enable Role": "کردار فعال کریں",
  "Cannot delete role with assigned users": "صارفین سے منسلک کردار حذف نہیں ہو سکتا",
  "Delete Role": "کردار حذف کریں",
  "Module Access Levels (NONE / VIEW / OPERATE / MANAGE / ADMIN):": "ماڈیول رسائی کی سطحیں:",
  "Set level…": "سطح منتخب کریں…",
  "Super Admin holds full access permanently so the platform can never be locked out.": "سپر ایڈمن کی اجازتیں مکمل اور محفوظ ہیں تاکہ نظام کبھی مقفل نہ ہو۔",
  "Audit note (why this change was made)…": "تبدیلی کی وجہ (آڈٹ لاگ کے لیے)…",
  "Restore Default": "ڈیفالٹ بحال کریں",
  "Search pages or permissions (e.g. settlements, reopen, invoices, fleet)…": "صفحات یا اجازتوں میں تلاش کریں…",
  "Granted": "عطا کردہ",
  "Sensitive (§19)": "حساس",
  "Visible in navigation": "مینیو میں نظر آتا ہے",
  "Hidden from user": "مکمل طور پر پوشیدہ",
  "View only": "صرف دیکھیں",
  "Hide page": "صفحہ چھپائیں",
  "Grant all": "سب فعال کریں",
  "Sensitive": "حساس",
  "Disabled Globally": "عالمی سطح پر غیر فعال",
  "System Users": "نظام کے صارفین",
  "Scope:": "دائرہ کار:",
  "Inherited": "کردار سے موروثی",
  "Rule: DENY overrides ALLOW and Role Permissions": "اصول: صریح ممانعت (DENY) اجازت اور کردار پر غالب ہے",
  "The primary Super Admin account has full permanent permissions and cannot be restricted.": "بنیادی سپر ایڈمن اکاؤنٹ مکمل اجازت رکھتا ہے اور محدود نہیں کیا جا سکتا۔",
  "Assigned Primary Role": "صارف کا بنیادی کردار",
  "User Data Scope Override (§8)": "صارف کے ڈیٹا کا دائرہ کار",
  "Inherit from Role": "کردار سے خودکار وراثت",
  "Reason for user permission override…": "صارف کی اجازت میں تبدیلی کی وجہ…",
  "Reset to Inherited": "موروثی حالت پر بحال کریں",
  "Save User Overrides": "صارف کی اجازتیں محفوظ کریں",
  "In Role": "کردار میں شامل",
  "Allow": "اجازت",
  "Deny": "ممانعت",
  "Grant Temporary Time-Bound Permission (§13)": "وقتی طور پر محدود عارضی اجازت دیں",
  "Automatically expires once the end timestamp is reached.": "مقررہ وقت ختم ہونے پر یہ اجازت خودکار طور پر ختم ہو جائے گی۔",
  "Target Type": "ہدف کی قسم",
  "User": "مخصوص صارف",
  "Target": "ہدف",
  "Permission": "عطا کردہ اجازت",
  "Expires At": "میعاد ختم ہونے کا وقت",
  "Reason for temporary grant…": "عارضی اجازت کی وجہ…",
  "Grant": "اجازت دیں",
  "No temporary permissions granted yet.": "ابھی تک کوئی عارضی اجازت درج نہیں۔",
  "Revoked": "منسوخ",
  "Expired": "ختم شدہ",
  "Until:": "تک:",
  "Revoke": "منسوخ کریں",
  "Global Permission Switchboard (§12)": "عالمی سطح پر اجازتوں کی فعالیت",
  "disabled": "غیر فعال",
  "Disabling a permission here suspends it across all non-Super-Admin roles and users without deleting it.": "یہاں کسی اجازت کو غیر فعال کرنے سے وہ تمام کرداروں کے لیے عارضی طور پر رک جاتی ہے۔",
  "Disabled (Click to Enable)": "غیر فعال",
  "Enabled": "فعال",
  "Permission Change Log": "اجازتوں کی تبدیلی کا ریکارڈ",
  "recorded changes": "درج تبدیلیاں",
  "No permission changes have been recorded yet.": "ابھی تک اجازتوں میں کوئی تبدیلی درج نہیں ہوئی۔",
  "System Admin": "سسٹم ایڈمن",
  "Reason:": "وجہ:",
  "Users Assigned to Role:": "کردار سے منسلک صارفین:",
  "No users currently assigned to this role.": "اس کردار سے کوئی صارف منسلک نہیں۔",
  "Customize User": "صارف کی تخصیص",
  "Create New Role": "نیا کردار بنائیں",
  "Role Code (English uppercase)": "کردار کا کوڈ",
  "Arabic Name": "عربی نام",
  "English Name": "انگریزی نام",
  "Description": "کردار کی تفصیل",
  "Default Data Scope": "ڈیٹا کا دائرہ کار",
  "Cancel": "منسوخ کریں",
  "Create Role": "کردار بنائیں",
  "Financial Ledger": "مالیاتی خلاصہ اور ٹرپ لیجر",
  "Invoices": "ٹیکس انوائسز",
  "Financial Settlements": "مالیاتی تصفیے",
  "Payments & Collections": "ادائیگیاں اور وصولیاں",
  "Financial Review": "مالیاتی جائزہ اور منظوری",
  "Invoice created": "انوائس کامیابی سے بن گئی",
  "Error": "خرابی",
  "Invoice approved": "انوائس منظور ہو گئی",
  "Tax invoice issued": "ٹیکس انوائس جاری کر دی گئی",
  "Settlement updated": "مالیاتی تصفیہ اپڈیٹ ہو گیا",
  "Settlement locked or denied": "تصفیہ مقفل ہے",
  "Settlement approved & locked": "مالیاتی تصفیہ منظور اور مقفل ہو گیا",
  "Approval failed": "منظوری ناکام",
  "Settlement reopened and logged in Audit Trail": "تصفیہ دوبارہ کھول دیا گیا اور آڈٹ لاگ میں درج ہو گیا",
  "Reopen denied": "دوبارہ کھولنے کی اجازت نہیں",
  "Payment recorded": "ادائیگی درج کر دی گئی",
  "Payment failed": "ادائیگی ناکام",
  "Payment receipt confirmed": "ادائیگی کی وصولی کی تصدیق ہو گئی",
  "Financial review performed": "مالیاتی جائزہ مکمل ہو گیا",
  "Financial review approved": "مالیاتی جائزہ منظور ہو گیا",
  "FINANCE & SETTLEMENTS": "مالیات، انوائسز اور تصفیے",
  "Financial Operations, Invoices, Settlements & Review": "مالیاتی آپریشنز، انوائسز، تصفیے اور مالیاتی جائزہ",
  "New Invoice": "نئی انوائس",
  "Record Payment": "ادائیگی درج کریں",
  "Total Revenue": "کل آمدنی",
  "Total Expenses": "کل اخراجات",
  "Commissions": "ڈرائیور کمیشن",
  "Net Profit": "خالص منافع",
  "Collected": "وصول شدہ رقم",
  "Balance Due": "واجب الادا بقایا",
  "Trip": "ٹرپ",
  "Customer": "کلائنٹ",
  "Commission": "کمیشن",
  "Paid": "ادا شدہ",
  "Tax Invoices Registry (§17)": "ٹیکس انوائسز کا ریکارڈ",
  "invoices": "انوائسز",
  "Invoice #": "انوائس نمبر",
  "Subtotal": "بنیادی رقم",
  "VAT (15%)": "ٹیکس",
  "Total": "کل رقم",
  "Actions": "اقدامات",
  "Approve": "منظور کریں",
  "Issue": "جاری کریں",
  "Financial Settlements (§16)": "ٹرپس کے مالیاتی تصفیے",
  "Approved settlements are locked and cannot be edited unless reopened by a user with REOPEN_SETTLEMENT.": "منظوری کے بعد تصفیہ مقفل ہو جاتا ہے اور صرف REOPEN_SETTLEMENT کی اجازت سے دوبارہ کھولا جا سکتا ہے۔",
  "Customer / Driver": "کلائنٹ / ڈرائیور",
  "Balance": "بقایا",
  "Settlement Status": "تصفیہ کی حالت",
  "Approval": "منظوری",
  "Settle / Edit": "تصفیہ / ترمیم",
  "Reopen Settlement": "تصفیہ دوبارہ کھولیں",
  "Payments & Receivables (§18)": "ادائیگیوں اور وصولیوں کا ریکارڈ",
  "records": "ریکارڈز",
  "Payment #": "سند نمبر",
  "Party": "فریق",
  "Direction": "نوعیت",
  "Amount": "رقم",
  "Method": "طریقہ",
  "Inbound Receipt": "کلائنٹ سے وصولی",
  "Driver Payout": "ڈرائیور کو ادائیگی",
  "Confirm Receipt": "وصولی کی تصدیق",
  "Financial Review & Audit Approval (§18)": "مالیاتی جائزہ اور آڈٹ منظوری",
  "Review Status": "جائزہ کی حالت",
  "Reviewed By": "جائزہ کنندہ",
  "Perform Review": "جائزہ لیں",
  "Approve Review": "جائزہ منظور کریں",
  "Reopen Approved Settlement": "منظور شدہ تصفیہ دوبارہ کھولیں",
  "Please enter the mandatory audit reason for reopening this approved settlement.": "براہ کرم منظور شدہ تصفیہ کو دوبارہ کھولنے کی لازمی وجہ درج کریں۔",
  "Audit reason…": "دوبارہ کھولنے کی وجہ…",
  "Confirm Reopen": "تصدیق کریں",
  "Update Trip Settlement": "ٹرپ کا مالیاتی تصفیہ اپڈیٹ کریں",
  "Paid Amount (SAR)": "ادا شدہ رقم",
  "Settlement Notes": "تصفیہ کے نوٹس",
  "Save Settlement": "محفوظ کریں",
  "Create Tax Invoice": "نئی ٹیکس انوائس بنائیں",
  "Trip ID": "ٹرپ آئی ڈی",
  "Amount before VAT (optional)": "ٹیکس سے پہلے کی رقم",
  "Create Invoice": "انوائس بنائیں",
  "Record Financial Payment": "مالیاتی ادائیگی درج کریں",
  "Amount (SAR)": "رقم (ریال)",
  "Save Payment": "محفوظ کریں",
};
