/**
 * Urdu strings for the organised app surfaces (§5-§16): mobile app settings,
 * user management forms, driver/client apps, the settings center and the
 * sign-in preview. Consumed by `ur.glossary.ts` alongside the shell/ops/mobile
 * maps so an Urdu session never shows English or Arabic UI copy.
 */
export const UR_ORGANIZATION: Record<string, string> = {
  /* ── Account & settings ─────────────────────────────────────────── */
  "Account data": "اکاؤنٹ ڈیٹا",
  "Account type": "اکاؤنٹ کی قسم",
  "Account status": "اکاؤنٹ کی حالت",
  "Account data, security and sessions": "اکاؤنٹ ڈیٹا، سیکیورٹی اور سیشنز",
  "Security & sessions": "سیکیورٹی اور سیشنز",
  "Encrypted session token": "خفیہ سیشن ٹوکن",
  "Signed in with an encrypted session token": "خفیہ سیشن ٹوکن کے ذریعے لاگ ان",
  "Every sign-in is recorded in the audit log": "ہر لاگ ان آڈٹ لاگ میں درج ہوتا ہے",
  "Under review": "زیرِ نظرثانی",
  "Active": "فعال",
  "Phone": "فون",
  "My account": "میرا اکاؤنٹ",
  "Settings": "سیٹنگز",
  "Settings & support": "سیٹنگز اور معاونت",
  "Sign out": "سائن آؤٹ",
  "Tap again to confirm": "تصدیق کے لیے دوبارہ دبائیں",
  "Personal information of the signed-in user": "لاگ ان صارف کی ذاتی معلومات",
  "Notifications": "اطلاعات",
  "No notifications yet.": "ابھی تک کوئی اطلاع نہیں۔",
  "Refresh": "تازہ کریں",
  "Loading…": "لوڈ ہو رہا ہے…",
  "Back": "واپس",
  "Current": "موجودہ",

  /* ── App settings ───────────────────────────────────────────────── */
  "App Settings": "ایپ سیٹنگز",
  "App settings": "ایپ سیٹنگز",
  "Language, appearance, time & date": "زبان، ظاہری شکل، وقت اور تاریخ",
  "Choose the interface language": "انٹرفیس کی زبان منتخب کریں",
  "Light · Dark · System": "لائٹ · ڈارک · سسٹم",
  "System": "سسٹم کے مطابق",
  "Follow the device colour scheme": "ڈیوائس کے رنگی نظام کی پیروی کریں",
  "Active theme": "فعال تھیم",
  "Time & date": "وقت اور تاریخ",
  "Clock and date display preferences": "گھڑی اور تاریخ دکھانے کی ترجیحات",
  "Time format": "وقت کا فارمیٹ",
  "24-hour or 12-hour clock": "۲۴ گھنٹے یا ۱۲ گھنٹے کی گھڑی",
  "Date format": "تاریخ کا فارمیٹ",
  "Gregorian display preference": "عیسوی تاریخ دکھانے کی ترجیح",
  "Preview": "معاينة",
  "App information": "ایپ کی معلومات",
  "Platform, establishment and system": "پلیٹ فارم، ادارہ اور نظام",
  "Platform": "پلیٹ فارم",
  "App version": "ایپ ورژن",
  "EJAZ Transport Establishment": "مؤسسة اعجاز ٹرانسپورٹ",
  "Unified fleet & logistics platform": "موحد فلیٹ اور لاجسٹکس پلیٹ فارم",
  "System environment": "سسٹم ماحول",
  "Production": "پروڈکشن",
  "Interface type": "انٹرفیس کی قسم",
  "Choose the interface authorized for your account": "اپنے اکاؤنٹ کے لیے مجاز انٹرفیس منتخب کریں",
  "Driver app": "ڈرائیور ایپ",
  "Client app": "کلائنٹ ایپ",

  /* ── Mobile apps & preview ──────────────────────────────────────── */
  "Mobile apps": "موبائل ایپس",
  "Trips, tracking, documents and account": "ٹرپس، ٹریکنگ، دستاویزات اور اکاؤنٹ",
  "Dispatch, trips, GPS and account": "ڈسپیچ، ٹرپس، GPS اور اکاؤنٹ",
  "Both apps run on the same backend, database, accounts and permissions — every action reflects across the whole system.":
    "دونوں ایپس ایک ہی بیک اینڈ، ڈیٹابیس، اکاؤنٹس اور اجازتوں پر چلتی ہیں — ہر عمل پورے نظام میں ظاہر ہوتا ہے۔",
  "Preview only": "معاينة فقط",
  "Preview mode — sign-in is disabled.": "وضع المعاينة — تسجيل الدخول معطّل.",
  "Sign-in screen preview": "سائن اِن اسکرین کی معاينة",
  "Preview only — sign-in and app entry are disabled.": "معاينة فقط — سائن اِن اور ایپ داخلہ معطل ہیں۔",
  "Shows exactly what an unauthenticated visitor sees. No control-room, driver-app or client-app entry buttons are included inside the preview.":
    "بالکل وہی دکھاتا ہے جو ایک غیر مصدقہ وزیٹر دیکھتا ہے۔ معاينة کے اندر کنٹرول روم، ڈرائیور ایپ یا کلائنٹ ایپ کے کوئی داخلہ بٹن نہیں ہیں۔",
  "Open the client app": "کلائنٹ ایپ کھولیں",
  "Open the driver app": "ڈرائیور ایپ کھولیں",

  /* ── System settings ────────────────────────────────────────────── */
  "Establishment identity": "ادارے کی شناخت",
  "Name, logos, contact data": "نام، لوگوز، رابطے کا ڈیٹا",
  "Users & staff": "صارفین اور عملہ",
  "Driver registry & licences": "ڈرائیور رجسٹری اور لائسنس",
  "Customers & merchants accounts": "کلائنٹس اور تاجروں کے اکاؤنٹس",
  "Registration requests & approvals": "رجسٹریشن کی درخواستیں اور منظوریاں",
  "Staff & admin accounts": "عملہ اور ایڈمن اکاؤنٹس",
  "Roles & permissions (RBAC)": "کردار اور اجازتیں (RBAC)",
  "Role": "کردار",
  "Create driver": "ڈرائیور شامل کریں",
  "Create customer": "کلائنٹ شامل کریں",
  "Review": "نظرثانی",
  "Enforced in the API on every call — hiding a button is never the protection.":
    "ہر کال پر API میں نافذ — بٹن چھپانا کبھی حفاظت نہیں ہے۔",
  "Example": "مثال",
  "Draft → Pending → Confirmed → Loading → In transit → Arrived → Delivered → Settled":
    "مسودة → معلق → مؤكدة → تحميل → في الطريق → وصلت → سُلّمت → مُسوّاة",
  "Numbers come only from the backend generator; cancellations, reopening and archiving follow the canonical state machine.":
    "نمبر صرف بیک اینڈ جنریٹر سے آتے ہیں؛ منسوخی، دوبارہ کھولنا اور آرکائو مقررہ اسٹیٹ مشین کی پیروی کرتے ہیں۔",
  "Four official body types + assets": "چار سرکاری باڈی اقسام + اثاثے",
  "Provider active": "فراہم کنندہ فعال",
  "Checking provider…": "فراہم کنندہ چیک ہو رہا ہے…",
  "GPS service is not configured": "GPS سروس ترتیب شدہ نہیں ہے",
  "Ledger, invoices & settlements": "کھاتہ، بل اور تسویے",
  "Waybills, PODs & permits": "وے بل، POD اور اجازت نامے",
  "PDF · Excel · Print": "PDF · Excel · پرنٹ",
  "Sensitive operations record": "حساس عملیات کا ریکارڈ",

  /* ── Driver app ─────────────────────────────────────────────────── */
  "Driver app ": "ڈرائیور ایپ ",
  "Welcome": "خوش آمدید",
  "On duty": "ڈیوٹی پر",
  "Assigned Vehicle:": "تخصیص شدہ گاڑی:",
  "Current trip": "موجودہ ٹرپ",
  "Open current trip": "موجودہ ٹرپ کھولیں",
  "No trips are assigned to you yet.": "ابھی تک آپ کو کوئی ٹرپ تخصیص نہیں ہوا۔",
  "Browse available trips": "دستیاب ٹرپس براؤز کریں",
  "Trips & Available Dispatch": "ٹرپس اور دستیاب ڈسپیچ",
  "All": "تمام",
  "Available": "دستیاب",
  "Confirmed": "مؤكدة",
  "In progress": "جاری",
  "Completed": "مکمل",
  "No trips in this list.": "اس فہرست میں کوئی ٹرپ نہیں۔",
  "No available trips right now.": "اس وقت کوئی ٹرپ دستیاب نہیں۔",
  "Accept trip": "ٹرپ قبول کریں",
  "Open": "کھولیں",
  "Trip number": "ٹرپ نمبر",
  "Route": "راستہ",
  "Status": "حالت",
  "Start trip (IN_TRANSIT)": "ٹرپ شروع کریں (IN_TRANSIT)",
  "Arrived at destination": "منزل پر پہنچ گئی",
  "Proof of delivery (POD)": "تسلیمی کا ثبوت (POD)",
  "No current trip selected.": "کوئی موجودہ ٹرپ منتخب نہیں۔",
  "Unable to send the trip request right now.": "اس وقت ٹرپ کی درخواست بھیجنا ممکن نہیں۔",
  "Unable to update the trip status.": "ٹرپ کی حالت تازہ کرنا ممکن نہیں۔",
  "Recipient name": "وصول کنندہ کا نام",
  "Recipient phone": "وصول کنندہ کا فون",
  "Delivery notes": "تسلیمی نوٹس",
  "The recipient signed digitally": "وصول کنندہ نے ڈیجیٹل طور پر دستخط کیے",
  "Recording…": "ریکارڈ ہو رہا ہے…",
  "Confirm delivery (POD)": "تسلیمی کی تصدیق (POD)",
  "Enter the recipient name and confirm the signature.": "وصول کنندہ کا نام درج کریں اور دستخط کی تصدیق کریں۔",
  "Confirm the recipient's digital signature first.": "پہلے وصول کنندہ کے ڈیجیٹل دستخط کی تصدیق کریں۔",
  "Proof of delivery recorded and the trip is closed.": "تسلیمی کا ثبوت ریکارڈ ہو گیا اور ٹرپ بند ہو گئی۔",
  "Start GPS": "GPS شروع کریں",
  "Stop GPS": "GPS روکیں",
  "No active trip": "کوئی فعال ٹرپ نہیں",
  "Latitude": "عرض البلد",
  "Longitude": "طول البلد",
  "Speed": "رفتار",
  "GPS service is not configured on the platform. Device GPS broadcasting still works; live fleet telemetry requires the provider setup.":
    "پلیٹ فارم پر GPS سروس ترتیب شدہ نہیں۔ ڈیوائس GPS نشریہ ابھی بھی کام کرتا ہے؛ براہ راست فلیٹ ٹیلی میٹری کے لیے فراہم کنندہ کی ترتیب درکار ہے۔",

  /* ── Client app ─────────────────────────────────────────────────── */
  "Client app ": "کلائنٹ ایپ ",
  "Active Trips": "فعال ٹرپس",
  "Search by trip number or city…": "ٹرپ نمبر یا شہر سے تلاش کریں…",
  "Request a trip": "ٹرپ کی درخواست کریں",
  "Please complete the required shipment fields.": "براہِ کرم درکار شپمنٹ فیلڈز مکمل کریں۔",
  "Trip request created — number": "ٹرپ کی درخواست بن گئی — نمبر",
  "status: awaiting operations review": "حالت: آپریشنز نظرثانی کا انتظار",
  "Submit trip request": "ٹرپ کی درخواست جمع کریں",
  "Submitting…": "جمع ہو رہا ہے…",
  "Origin city": "شہرِ مبدا",
  "Destination city": "شہرِ منزل",
  "Pickup address": "پک اپ پتہ",
  "Delivery address": "تسلیمی کا پتہ",
  "Cargo description": "مال کی تفصیل",
  "Weight (tons)": "وزن (ٹن)",
  "Truck body type": "ٹرک باڈی کی قسم",
  "From (Loading)": "نقطۂ لوڈنگ",
  "To (Delivery)": "نقطۂ تسلیم",
  "Cargo:": "مال:",
  "Track Live Location Now": "ابھی براہ راست مقام تلاش کریں",
  "My Shipments": "میری شپمنٹس",
  "View All": "سب دیکھیں",
  "My trips": "میرے ٹرپس",
  "My Trips": "میرے ٹرپس",
  "Tracking": "ٹریکنگ",
  "No trips yet.": "ابھی تک کوئی ٹرپ نہیں۔",
  "Trips": "ٹرپس",
  "Driver:": "ڈرائیور:",
  "Driver not assigned": "ڈرائیور تخصیص نہیں",
  "Documents": "دستاویزات",
  "Open Tracking": "ٹریکنگ کھولیں",
  "Shipment Tracking": "شپمنٹ ٹریکنگ",
  "GPS service is not configured on the platform. Live vehicle telemetry will appear here once the GPS provider is set up.":
    "پلیٹ فارم پر GPS سروس ترتیب شدہ نہیں۔ GPS فراہم کنندہ ترتیب ہوتے ہی گاڑی کی براہ راست ٹیلی میٹری یہاں ظاہر ہوگی۔",
  "Select a trip to track.": "ٹریکنگ کے لیے ٹرپ منتخب کریں۔",
  "Vehicle & Plate:": "گاڑی اور پلیٹ:",
  "Telemetry Status:": "ٹیلی میٹری حالت:",
  "GPS Telemetry Online": "GPS ٹیلی میٹری آن لائن",
  "Shipment Documents & POD": "شپمنٹ دستاویزات اور POD",
  "Official documentation for trip": "ٹرپ کی سرکاری دستاویزات",
  "Electronic Waybill (BOL)": "الیکٹرانک وے بل (BOL)",
  "Not published yet": "ابھی تک شائع نہیں",
  "Proof of Delivery (POD)": "تسلیمی کا ثبوت (POD)",
  "Delivery confirmed": "تسلیمی کی تصدیق ہو گئی",
  "Recipient": "وصول کنندہ",
  "Recorded": "ریکارڈ شدہ",
  "Awaiting delivery confirmation": "تسلیمی کی تصدیق کا انتظار",
  "The driver records the POD at handover": "ڈرائیور ہینڈ اوور پر POD ریکارڈ کرتا ہے",
  "Contact support": "سپورٹ سے رابطہ",
  "Operations desk": "آپریشنز ڈیسک",

  /* ── User management & forms ────────────────────────────────────── */
  "User management": "صارف کا انتظام",
  "Available because your account holds the required permissions": "دستیاب ہے کیونکہ آپ کے اکاؤنٹ کے پاس درکار اجازتیں ہیں",
  "Add new driver": "نیا ڈرائیور شامل کریں",
  "Add new customer": "نیا کلائنٹ شامل کریں",
  "Sends the request to the control room for review": "درخواست نظرثانی کے لیے کنٹرول روم بھیجی جاتی ہے",
  "Unable to load the form. Check the connection.": "فارم لوڈ نہیں ہو سکا۔ کنکشن چیک کریں۔",
  "Please complete the required fields.": "براہِ کرم درکار فیلڈز مکمل کریں۔",
  "Account password must be at least 8 characters.": "اکاؤنٹ پاس ورڈ کم از کم ۸ حروف کا ہونا چاہیے۔",
  "Passwords do not match.": "پاس ورڈ مماثل نہیں ہیں۔",
  "The request was submitted — status: processing. It is now in the control room for review.":
    "درخواست جمع ہو گئی — حالت: زیرِ عمل۔ یہ اب نظرثانی کے لیے کنٹرول روم میں ہے۔",
  "Unable to submit the request.": "درخواست جمع نہیں ہو سکی۔",
  "Select…": "منتخب کریں…",
  "Account password (8+ characters)": "اکاؤنٹ پاس ورڈ (۸+ حروف)",
  "Confirm password": "پاس ورڈ کی تصدیق",
  "Attached": "منسلک",
  "Attach": "منسلک کریں",
  "Missing documents": "غائب دستاویزات",
  "Submit driver request": "ڈرائیور درخواست جمع کریں",
  "Submit customer request": "کلائنٹ درخواست جمع کریں",

  /* Reports & analytics (§25) + honest GPS labels (§24) */
  "Reports & analytics": "رپورٹیں و تجزیات",
  "Real operational & financial data from the enterprise backend": "حقیقی آپریشنل و مالی ڈیٹا مرکزی بیک اینڈ سے",
  "Print": "پرنٹ",
  "Month (YYYY-MM)": "مہینہ (YYYY-MM)",
  "Min revenue (SAR)": "کم از کم آمدنی (ریال)",
  "Loading real report data…": "حقیقی رپورٹ ڈیٹا لوڈ ہو رہا ہے…",
  "Trips (filtered)": "سفر (فلٹر شدہ)",
  "Gross revenue (SAR)": "مجموعی آمدنی (ریال)",
  "Expenses (SAR)": "اخراجات (ریال)",
  "Payments (SAR)": "ادائیگیاں (ریال)",
  "Total trips": "کل سفر",
  "Utilization": "استعمال کی شرح",
  "Revenue": "آمدنی",
  "Expenses": "اخراجات",
  "No trips match the selected filters.": "منتخب فلٹرز سے مطابقت رکھنے والا کوئی سفر نہیں۔",
  "Report generated from live data": "رپورٹ براہ راست ڈیٹا سے تیار کی گئی",
  "Maps Dev Adapter · route preview": "نقشہ ایڈاپٹر · راستے کا پیش منظر",
  "GPS service is not configured — vehicle positions shown are route demos, not live GPS.":
    "GPS سروس ترتیب شدہ نہیں — ظاہر کردہ گاڑیوں کی پوزیشنیں راستے کی مظاہرے ہیں، حقیقی GPS نہیں۔",
  "Speed (route demo)": "رفتار (مظاہرہ)",
  "Route demo moving · not live GPS": "راستے کا مظاہرہ متحرک · حقیقی GPS نہیں",
  "Route demo paused": "راستے کا مظاہرہ روک دیا گیا",
  "Pause demo": "مظاہرہ روکیں",
  "Resume demo": "مظاہرہ جاری کریں",
  "Vehicle": "گاڑی",
  "Payments": "ادائیگیاں",
  "Unable to reach the reporting service.": "رپورٹنگ سروس تک رسائی ممکن نہیں۔",
  /* ── Roles & permissions administration (RBAC) ──────────────────── */
  "Roles & permissions": "کردار اور اختیارات",
  "Control exactly which sections, pages and functions each role sees. Changes apply on save — no code edit.":
    "طے کریں کہ ہر کردار کون سے سیکشن، صفحات اور افعال دیکھ سکتا ہے۔ تبدیلیاں محفوظ کرتے ہی لاگو ہو جاتی ہیں — کوڈ میں ترمیم کے بغیر۔",
  "Loading the permission registry…": "اختیارات کا رجسٹر لوڈ ہو رہا ہے…",
  "Unable to load the permission registry.": "اختیارات کا رجسٹر لوڈ نہیں ہو سکا۔",
  "Retry": "دوبارہ کوشش کریں",
  "Roles": "کردار",
  "edited": "ترمیم شدہ",
  "The system administrator holds full access and cannot be restricted — otherwise nobody could restore access. Edit any other role to control what it sees.":
    "سسٹم ایڈمنسٹریٹر کے پاس مکمل رسائی ہے اور اسے محدود نہیں کیا جا سکتا — ورنہ کوئی بھی رسائی بحال نہ کر سکے گا۔ کسی دوسرے کردار کو ترتیب دیں۔",
  "Search a page or function…": "صفحہ یا فعل تلاش کریں…",
  "granted": "دیے گئے",
  "Restore defaults": "طے شدہ بحال کریں",
  "Save permissions": "اختیارات محفوظ کریں",
  "Saving…": "محفوظ ہو رہا ہے…",
  "Permissions saved": "اختیارات محفوظ ہو گئے",
  "Permissions saved for": "اختیارات محفوظ ہو گئے برائے",
  "added": "شامل",
  "removed": "ہٹائے گئے",
  "Saving failed.": "محفوظ کرنے میں ناکامی۔",
  "Default permissions restored.": "طے شدہ اختیارات بحال ہو گئے۔",
  "Reset failed.": "بحالی ناکام۔",
  "pages": "صفحات",
  "Whole section": "پورا سیکشن",
  "Permission change log": "اختیارات کی تبدیلی کا لاگ",
  "Who changed which role, from what to what, and when.": "کس نے کس کردار کو، کس سے کیا، اور کب تبدیل کیا۔",
  "No permission changes recorded yet.": "ابھی تک اختیارات میں کوئی تبدیلی درج نہیں ہوئی۔",
  "restored defaults": "طے شدہ بحال",
  "updated": "تبدیل شدہ",
  "Show or hide any section, page or function for any role — applied on save.":
    "کسی بھی کردار کے لیے کوئی بھی سیکشن، صفحہ یا فعل دکھائیں یا چھپائیں — محفوظ کرتے ہی لاگو۔",
  "The system administrator holds full access and cannot be restricted":
    "سسٹم ایڈمنسٹریٹر کے پاس مکمل رسائی ہے اور اسے محدود نہیں کیا جا سکتا",
};
