/**
 * Urdu glossary — part 1/4 · product shell, navigation, dashboards, actions.
 *
 * The console has ~1000 legacy `t("English", "العربية")` call sites. Rather than
 * rewriting every one of them, `settings.tsx` resolves Urdu through this
 * glossary: `t(en, ar)` in Urdu mode looks up the English source string, then
 * the Arabic one, and only then falls back. New surfaces use keys from
 * `i18n.ts` instead — this file exists so the pre-existing screens are fully
 * Urdu too, with no Arabic left inside an Urdu session.
 */
export const UR_SHELL: Record<string, string> = {
  /* Navigation & sections */
  "Logistics Dashboard": "ڈیش بورڈ",
  "Operations Center": "آپریشنز سینٹر",
  "Trips": "ٹرپس",
  "Shipments": "کھیپ",
  "Live Map": "لائیو نقشہ",
  "Fleet": "فلیٹ",
  "Fleet (4 Types)": "فلیٹ (چار اقسام)",
  "Vehicle Assets": "گاڑیوں کے اثاثے",
  "Drivers": "ڈرائیورز",
  "Registration Requests": "رجسٹریشن درخواستیں",
  "Reports & Audit": "رپورٹس اور آڈٹ",
  "Fleet Analytics": "فلیٹ تجزیات",
  "Trip Archive": "ٹرپ آرکائیو",
  "Settings & Identity": "سیٹنگز اور شناخت",
  "Branding": "برانڈنگ",
  "Chats & Dispatch": "پیغامات اور ڈسپیچ",
  "AI Logistics Assistant": "اعجاز اسسٹنٹ",
  "Live Smart Alerts": "سمارٹ الرٹس",
  "Reports": "رپورٹس",
  "Operations": "آپریشنز",
  "Insights": "تجزیات",
  "Quick create": "فوری تخلیق",
  "Dispatch, repair or report": "ڈسپیچ، مرمت یا رپورٹ",
  "Create new Request": "نئی درخواست بنائیں",
  "Create new request": "نئی درخواست بنائیں",
  "Open navigation menu": "نیویگیشن مینیو کھولیں",
  "Opens in a window": "ونڈو میں کھلتا ہے",
  "Control Room": "کنٹرول روم",
  "Control Room Sign-in": "کنٹرول روم سائن اِن",

  /* Header & shell */
  "Heavy Fleet & Logistics Control": "ہیوی فلیٹ اور لاجسٹکس کنٹرول",
  "AI Assistant": "اسسٹنٹ",
  "Open AI Logistics Assistant": "اعجاز اسسٹنٹ کھولیں",
  "Switch language (العربية / English / اردو)": "زبان تبدیل کریں (العربية / English / اردو)",
  "Select Language": "زبان منتخب کریں",
  "Toggle day / night": "دن / رات موڈ",
  "Toggle Theme": "تھیم تبدیل کریں",
  "Switch Account": "اکاؤنٹ تبدیل کریں",
  "Switch Demo Account / View": "ڈیمو اکاؤنٹ یا ویو تبدیل کریں",
  "Instant Role Switcher": "فوری کردار تبدیلی",
  "Preview Login Screen": "سائن اِن اسکرین دیکھیں",
  "active trucks on road": "ٹرکس سڑک پر فعال",
  "active trips synced": "ٹرپس مطابقت پذیر",
  "Control Panel & Admin": "کنٹرول پینل اور ایڈمن",
  "Mobile App (Driver/Client)": "موبائل ایپ (ڈرائیور/کلائنٹ)",
  "Since 2022": "قیام ۲۰۲۲",
  "Your Cargo.. Our Responsibility": "آپ کا سامان.. ہماری ذمہ داری",
  "Live Data": "لائیو ڈیٹا",
  "Persona Mode:": "کردار موڈ:",
  "Fleet Admin": "فلیٹ ایڈمن",
  "Driver Portal": "ڈرائیور پورٹل",
  "Shipper Portal": "کلائنٹ پورٹل",
  "Fleet Owner": "فلیٹ مالک",
  "Live GPS Engine Running": "لائیو ٹریکنگ انجن فعال",
  "Simulation Paused": "نقلی حرکت روکی گئی",
  "Pause GPS": "روکیں",
  "Resume GPS": "دوبارہ چلائیں",

  /* Common actions */
  "All": "تمام",
  "All Types": "تمام اقسام",
  "All Status": "تمام حالتیں",
  "Status": "حالت",
  "Type": "قسم",
  "Actions": "اقدامات",
  "Action": "کارروائی",
  "Save": "محفوظ کریں",
  "Saving...": "محفوظ ہو رہا ہے...",
  "Cancel": "منسوخ",
  "Confirm": "تصدیق",
  "Confirm & Save Vehicle": "گاڑی محفوظ کریں",
  "Close": "بند کریں",
  "Done": "مکمل",
  "Delete": "حذف کریں",
  "Edit": "ترمیم",
  "Change": "تبدیل کریں",
  "Clear": "صاف کریں",
  "Reset filters": "فلٹر صاف کریں",
  "Filters reset": "فلٹرز صاف ہو گئے",
  "Send": "بھیجیں",
  "Sending…": "بھیجا جا رہا ہے…",
  "Search": "تلاش",
  "Refresh": "تازہ کریں",
  "Refreshing…": "تازہ کیا جا رہا ہے…",
  "Loading": "لوڈ ہو رہا ہے",
  "Loading...": "لوڈ ہو رہا ہے...",
  "Loading…": "لوڈ ہو رہا ہے…",
  "Uploading...": "اپ لوڈ ہو رہا ہے...",
  "Uploading…": "اپ لوڈ ہو رہا ہے…",
  "Publishing…": "شائع ہو رہا ہے…",
  "Adding...": "شامل کیا جا رہا ہے...",
  "Link Copied!": "لنک کاپی ہو گیا!",
  "Copy Link": "لنک کاپی کریں",
  "Copy Phone Number": "فون نمبر کاپی کریں",
  "Phone number copied to clipboard": "فون نمبر کاپی ہو گیا",
  "Export": "برآمد کریں",
  "Export Ledger": "لیجر برآمد کریں",
  "Export ready": "برآمد تیار ہے",
  "Print / Save PDF": "پی ڈی ایف محفوظ کریں",
  "Print e-Waybill": "ای بارنامہ پرنٹ کریں",
  "Print Waybill": "بارنامہ پرنٹ کریں",
  "Share Tracking Link": "ٹریکنگ لنک شیئر کریں",
  "Menu": "مینیو",
  "More": "مزید",
  "Open": "کھولیں",
  "View Details": "تفصیلات دیکھیں",
  "View All": "سب دیکھیں",
  "Show": "دکھائیں",
  "Showing all shipments": "تمام کھیپ دکھائی جا رہی ہیں",
  "Zoom In": "زوم اِن",
  "Zoom Out": "زوم آؤٹ",
  "Recenter": "دوبارہ مرکز کریں",
  "Track": "ٹریک کریں",
  "Track on Live Map": "لائیو نقشے پر دیکھیں",
  "Track Live Trip": "لائیو ٹرپ ٹریک کریں",
  "Track Live Location Now": "ابھی لائیو مقام دیکھیں",
  "Open Live Map": "لائیو نقشہ کھولیں",
  "Open Tracking": "ٹریکنگ کھولیں",
  "Open Trip Details": "ٹرپ تفصیلات کھولیں",
  "Open Trip Actions & Roadmap": "ٹرپ اقدامات اور روڈ میپ کھولیں",
  "Open Google Maps": "گوگل میپ میں کھولیں",
  "Required Field": "لازمی خانہ",
  "Yes": "ہاں",
  "No": "نہیں",
  "None": "کوئی نہیں",
  "Optional": "اختیاری",
  "Pending": "زیرِ التواء",
  "Approved": "منظور شدہ",
  "Rejected": "مسترد",
  "Verified": "تصدیق شدہ",
  "Verified & Valid": "تصدیق شدہ اور درست",
  "Official": "سرکاری",
  "OFFICIAL": "سرکاری",
  "BASELINE": "بنیادی",
  "Custom": "حسبِ ضرورت",
  "custom": "حسبِ ضرورت",

  /* Trip / shipment lifecycle & statuses */
  "On Road": "راستے میں",
  "On Route": "راستے میں",
  "on route": "راستے میں",
  "In Transit": "راستے میں",
  "Available": "دستیاب",
  "Available / Idle": "دستیاب / فارغ",
  "Active": "فعال",
  "Active on Route": "راستے میں فعال",
  "Active on Duty": "ڈیوٹی پر فعال",
  "Active Trips": "فعال ٹرپس",
  "Inactive": "غیر فعال",
  "Waiting": "انتظار میں",
  "Waiting / Loading": "انتظار / لوڈنگ",
  "Waiting / Loading...": "انتظار / لوڈنگ...",
  "Maintenance": "مرمت",
  "Maintenance / Idle": "مرمت / فارغ",
  "Under Maintenance": "مرمت میں",
  "Cancelled": "منسوخ",
  "Completed": "مکمل",
  "Delivered": "ڈیلیور شدہ",
  "Delivered & Closed": "ڈیلیور اور بند",
  "Scheduled": "شیڈول شدہ",
  "Loaded": "لوڈ ہو گیا",
  "Transit hub": "ٹرانزٹ مرکز",
  "New assignment": "نئی ڈیوٹی",
  "Arrived": "پہنچ گیا",
  "Idle": "فارغ",
  "Rest": "آرام",
  "Leave": "چھٹی",
  "Shift": "شفٹ",
  "Destination": "منزل",
  "Origin": "نقطہ آغاز",
  "From": "سے",
  "To": "تک",
  "From (Loading)": "سے (لوڈنگ)",
  "To (Delivery)": "تک (ترسیل)",
  "Route": "راستہ",
  "Route Corridor": "راستہ کوریڈور",
  "Corridor & Route": "کوریڈور اور راستہ",
  "Corridor & Speed:": "کوریڈور اور رفتار:",
  "Stops": "ٹھہراؤ",
  "ETA": "متوقع آمد",
  "Estimated Arrival (ETA)": "متوقع آمد کا وقت",
  "Distance": "فاصلہ",
  "Remaining Distance": "باقی فاصلہ",
  "Progress": "پیش رفت",
  "Trip Progress": "ٹرپ کی پیش رفت",
  "Speed": "رفتار",
  "Ground Speed": "زمینی رفتار",
  "Fuel": "ایندھن",
  "Fuel level": "ایندھن کی سطح",
  "Fuel Tank": "ایندھن ٹینک",
  "Engine": "انجن",
  "Engine power": "انجن پاور",
  "Engine temp": "انجن کا درجہ حرارت",
  "Box temp": "کنٹینر درجہ حرارت",
  "Reefer Box Temp": "کنٹینر درجہ حرارت",
  "Odometer": "اوڈومیٹر",
  "Plate": "پلیٹ",
  "Plate Number": "پلیٹ نمبر",
  "Payload": "وزن",
  "Payload Weight": "وزن",
  "Load": "لوڈ",
  "Load ratio": "لوڈ تناسب",
  "Capacity": "گنجائش",
  "Free space": "باقی گنجائش",
  "Max load": "زیادہ سے زیادہ وزن",
  "Max Payload": "زیادہ سے زیادہ وزن",
  "Current Truck Capacity": "ٹرک کی موجودہ گنجائش",
  "Current Status:": "موجودہ حالت:",
  "Trip Details": "ٹرپ تفصیلات",
  "Trip Control": "ٹرپ کنٹرول",
  "Trip Archive & Operational Audit Log": "ٹرپ آرکائیو اور آپریشنل آڈٹ لاگ",
  "Trip Management & Consignment Lifecycle": "ٹرپ اور کھیپ کے مراحل کا انتظام",
  "Assigned Vehicle": "مقرر گاڑی",
  "Assigned Truck": "مقرر ٹرک",
  "Assigned Truck:": "مقرر ٹرک:",
  "Assigned Vehicle:": "مقرر گاڑی:",
  "Unassigned": "غیر مقرر",
  "Assigned Heavy Vehicle": "مقرر بھاری گاڑی",
  "Driver": "ڈرائیور",
  "Driver:": "ڈرائیور:",
  "Driver Name": "ڈرائیور کا نام",
  "Primary Driver": "بنیادی ڈرائیور",
  "Replace Driver": "ڈرائیور تبدیل کریں",
  "Change Driver": "ڈرائیور تبدیل کریں",
  "Replace Truck": "ٹرک تبدیل کریں",
  "Current Truck": "موجودہ ٹرک",
  "Contact Driver": "ڈرائیور سے رابطہ",
  "Call Cellular Phone": "موبائل پر کال کریں",
  "Customer": "کلائنٹ",
  "Shipper": "ارسال کنندہ",
  "Consignee": "وصول کنندہ",
  "Consignee:": "وصول کنندہ:",
  "Owner": "مالک",
  "Cargo": "کھیپ",
  "Cargo:": "کھیپ:",
  "Cargo Weight": "کھیپ کا وزن",
  "Tons": "ٹن",
  "tons": "ٹن",
  "t payload": "ٹن وزن",
  "Out for delivery": "ترسیل کے لیے روانہ",
  "Proof of Delivery (POD)": "ثبوتِ ترسیل (POD)",
  "Capture POD Signature": "POD دستخط لیں",
  "Sign Proof of Delivery (POD)": "ثبوتِ ترسیل پر دستخط",
  "Consignee Digital Signature (POD)": "وصول کنندہ کے ڈیجیٹل دستخط (POD)",
  "Confirm Delivery": "ترسیل کی تصدیق",
  "View Waybill & POD": "بارنامہ اور POD دیکھیں",
  "Trip Event Audit & Milestone Timeline": "ٹرپ واقعات اور سنگِ میل ٹائم لائن",
  "Change Trip Milestone Lifecycle": "ٹرپ کے مرحلے تبدیل کریں",
  "Mark Ready": "تیار نشان زد کریں",
  "Start Trip / Depart": "ٹرپ شروع کریں / روانہ",
  "Log Rest / Idle": "آرام / قیام درج کریں",
  "Confirm Arrival": "آمد کی تصدیق",
  "Pending Driver Request": "ڈرائیور کی زیرِ التواء درخواست",
  "Driver submitted request to be assigned to this trip": "ڈرائیور نے اس ٹرپ کے لیے درخواست بھیجی",
  "Approve & Assign Trip": "منظور اور ٹرپ مقرر کریں",
  "Decline Request": "درخواست مسترد کریں",
  "Driver trip request approved successfully! Trip is now confirmed.": "ڈرائیور کی درخواست منظور — ٹرپ تصدیق شدہ۔",
  "Failed to approve driver request": "ڈرائیور کی درخواست منظور نہ ہو سکی",
  "Driver trip request rejected.": "ڈرائیور کی درخواست مسترد کر دی گئی۔",
  "Failed to reject driver request": "ڈرائیور کی درخواست مسترد نہ ہو سکی",
  "New request created, please confirm pickup.": "نئی درخواست بن گئی، پک اپ کی تصدیق کریں۔",

  /* KPI / analytics */
  "Total Shipments": "کل کھیپ",
  "Total shipments": "کل کھیپ",
  "Total Freight Volume": "کل مال کی مقدار",
  "Growth vs prev period": "پچھلی مدت سے اضافہ",
  "growth vs prev period": "پچھلی مدت سے اضافہ",
  "Operating Revenue (SAR)": "آپریٹنگ آمدنی (ریال)",
  "revenue efficiency": "آمدنی کی کارکردگی",
  "Ton-Kilometer Throughput": "ٹن-کلومیٹر تھروپٹ",
  "T-Km": "ٹن-کلومیٹر",
  "Across 5 Saudi Corridors": "پانچ سعودی کوریڈورز پر",
  "Fleet On-Time Delivery": "وقت پر ترسیل",
  "Industry benchmark: 91%": "صنعتی معیار: ۹۱٪",
  "Trip Volume & Freight Activity Trend": "ٹرپ حجم اور مال کی نقل و حرکت",
  "Interactive data-driven trip execution curve": "ڈیٹا پر مبنی ٹرپ عمل کا گراف",
  "Trips Total": "کل ٹرپس",
  "Fleet Status Breakdown": "فلیٹ حالت کی تفصیل",
  "Heavy Tractor Units": "بھاری ٹریکٹر یونٹس",
  "Top Fleet Drivers Performance Leaderboard": "بہترین ڈرائیورز کی فہرست",
  "Ranked by safety index, on-time rate, and completed hauls": "حفاظت، وقت کی پابندی اور مکمل ٹرپس کے مطابق",
  "Certified Drivers": "تصدیق شدہ ڈرائیورز",
  "Completed Trips": "مکمل ٹرپس",
  "Safety Rating": "حفاظتی درجہ بندی",
  "On-Time Rate": "وقت کی پابندی",
  "Total Drivers": "کل ڈرائیورز",
  "On Highway": "شاہراہ پر",
  "Rest / Leave": "آرام / چھٹی",
  "Fleet size": "فلیٹ کا حجم",
  "On-time rate": "وقت کی پابندی",
  "Avg. fuel": "اوسط ایندھن",
  "Utilisation by body type": "گاڑی کی قسم کے مطابق استعمال",
  "Average payload fill across the fleet": "فلیٹ میں اوسط وزن",
  "Fleet Utilisation": "فلیٹ کا استعمال",
  "Fleet Utilization": "فلیٹ کا استعمال",
  "vs last week": "پچھلے ہفتے کے مقابلے",
  "On-Time Probability": "وقت پر ترسیل کے امکانات",
  "active trips tracked": "زیرِ نگرانی ٹرپس",
  "Reefer Safety Index": "کولڈ چین حفاظتی اشاریہ",
  "0 temperature deviations": "درجہ حرارت میں کوئی انحراف نہیں",
  "Active Fleet Summary & AI Assessment": "فلیٹ کی مکمل صورتحال اور AI جائزہ",
  "Driver Profile & Logistics Card": "ڈرائیور پروفائل اور لاجسٹکس کارڈ",
  "Regulatory & Transport Authority Compliance": "نقل و حمل اتھارٹی کے تقاضے",
  "National ID / Iqama": "قومی شناخت / اقامہ",
  "Heavy Transport License": "بھاری ٹرانسپورٹ لائسنس",
  "License Expiry Date": "لائسنس کی میعاد",
  "License Number": "لائسنس نمبر",
  "Medical Fitness": "طبی فٹنس",
  "Vehicle Category": "گاڑی کی قسم",
  "Model & Power": "ماڈل اور پاور",
  "Rating & Trips": "درجہ بندی اور ٹرپس",
  "completed trips": "مکمل ٹرپس",
  "View Vehicle in Fleet Manager": "فلیٹ مینیجر میں گاڑی دیکھیں",
  "No truck currently assigned to this driver": "اس ڈرائیور کو کوئی ٹرک مقرر نہیں",
  "Active Highway Trip": "شاہراہ پر فعال ٹرپ",
  "Fleet Drivers & Crew Control": "ڈرائیورز اور عملے کا انتظام",
  "Driver allocation, regulatory certifications, and live road dispatch status": "ڈیوٹی تقسیم، سرٹیفیکیشن اور لائیو ڈسپیچ حالت",
  "Driver Request": "ڈرائیور کی درخواست",
  "All Customer Trips": "تمام کلائنٹ ٹرپس",
  "Client Portal": "کلائنٹ پورٹل",
  "My Shipments": "میری کھیپ",
  "Search by Trip Number (e.g. EJ-2026-000125)...": "ٹرپ نمبر سے تلاش کریں (مثلاً EJ-2026-000125)...",
  "No active shipments under your account": "آپ کے اکاؤنٹ میں کوئی فعال کھیپ نہیں",
  "No shipments yet.": "ابھی کوئی کھیپ نہیں۔",
  "No shipments found": "کوئی کھیپ نہیں ملی",
  "No shipments match these filters.": "ان فلٹرز سے کوئی کھیپ مطابقت نہیں رکھتی۔",
  "Nothing matches the current brand, partner or status filters.": "موجودہ فلٹرز سے کچھ مطابقت نہیں رکھتا۔",
  "Live GPS Tracking": "لائیو جی پی ایس ٹریکنگ",
  "Updated 20s ago": "۲۰ سیکنڈ پہلے اپ ڈیٹ",
  "Vehicle & Plate:": "گاڑی اور پلیٹ:",
  "Telemetry Status:": "ٹیلی میٹری حالت:",
  "GPS Telemetry Online": "جی پی ایس ٹیلی میٹری آن لائن",
  "Shipment Documents & POD": "کھیپ دستاویزات اور POD",
  "Official electronically signed documentation for": "الیکٹرانک دستخط شدہ سرکاری دستاویز برائے",
  "Electronic Waybill (BOL)": "الیکٹرانک بارنامہ (BOL)",
  "Received in good condition matching SASO standards. Digital signature and confirmation code verified.": "SASO معیار کے مطابق صحیح حالت میں موصول۔ ڈیجیٹل دستخط اور تصدیقی کوڈ کی تصدیق ہو گئی۔",
  "Recipient:": "وصول کنندہ:",
  "Signed Digitally": "ڈیجیٹل دستخط شدہ",
  "Client Account": "کلائنٹ اکاؤنٹ",
  "Commercial Reg (CR):": "تجارتی رجسٹریشن:",
  "VAT Tax Number:": "ویٹ ٹیکس نمبر:",
  "System Role:": "نظام میں کردار:",
  "Sign Out from Client Account": "کلائنٹ اکاؤنٹ سے سائن آؤٹ",
  "Sign Out from Driver Account": "ڈرائیور اکاؤنٹ سے سائن آؤٹ",
  "Driver Terminal": "ڈرائیور ٹرمینل",
  "Active Assignment": "فعال ڈیوٹی",
  "Loading Terminal": "لوڈنگ ٹرمینل",
  "Destination Discharge": "منزل پر اتار",
  "No active trip currently assigned to you": "اس وقت آپ کو کوئی فعال ٹرپ نہیں دیا گیا",
  "Field Driver GPS Broadcast": "ڈرائیور کی لائیو جی پی ایس نشریات",
  "Live device location transmitting": "ڈیوائس کا مقام براہِ راست بھیجا جا رہا ہے",
  "GPS telemetry paused": "جی پی ایس ٹیلی میٹری روکی گئی",
  "Stop GPS": "جی پی ایس بند کریں",
  "Start GPS": "جی پی ایس شروع کریں",
  "Driver Fleet Schedule": "ڈرائیور شیڈول",
  "Trips & Available Dispatch": "ٹرپس اور دستیاب ڈسپیچ",
  "Confirmed": "تصدیق شدہ",
  "No open trips currently available for request": "درخواست کے لیے کوئی کھلا ٹرپ دستیاب نہیں",
  "No trips found in this category": "اس قسم میں کوئی ٹرپ نہیں ملا",
  "Check back shortly or contact Operations Dispatch": "تھوڑی دیر بعد دیکھیں یا آپریشنز سے رابطہ کریں",
  "Request Pending Operations Review": "درخواست آپریشنز کے جائزے میں",
  "Request Trip Assignment": "ٹرپ کے لیے درخواست دیں",
  "Current Stage & Authorized Actions": "موجودہ مرحلہ اور مجاز اقدامات",
  "Start Heading to Loading Bay": "لوڈنگ بے کی طرف روانہ ہوں",
  "Confirm Arrived at Loading Bay": "لوڈنگ بے پر آمد کی تصدیق",
  "Confirm Cargo Loaded & Strapped": "کھیپ لوڈ اور بندھنے کی تصدیق",
  "Depart & Start Highway Transit": "روانہ ہو کر سفر شروع کریں",
  "Confirm Arrived at Destination": "منزل پر آمد کی تصدیق",
  "Proceed to Delivery & Sign POD": "ترسیل مکمل کر کے POD پر دستخط کریں",
  "Trip Delivered & Completed Successfully": "ٹرپ کامیابی سے مکمل اور ڈیلیور",
  "Driver Route Navigation": "ڈرائیور روٹ نیویگیشن",
  "Enter recipient info and capture digital sign-off for": "وصول کنندہ کی معلومات دیں اور دستخط لیں برائے",
  "Driver Profile": "ڈرائیور پروفائل",
  "Driver Field Actions": "ڈرائیور کے میدانی اقدامات",
  "Confirm Loading": "لوڈنگ کی تصدیق",
  "Log Rest Stop": "آرام درج کریں",
  "Arrived at Gate": "گیٹ پر پہنچ گئے",
  "Complete Delivery": "ترسیل مکمل کریں",
  "Start Trip Departure": "ٹرپ روانگی شروع کریں",
  "Navigation Guidance": "نیویگیشن ہدایات",
  "Turn left after 400m onto Highway 40 Express towards Taif": "۴۰۰ میٹر بعد بائیں مڑیں شاہراہ ۴۰ کی طرف طائف",
  "Legal Limit: 90 km/h": "قانونی حد: ۹۰ کلومیٹر فی گھنٹہ",
  "Truck Telemetry & Sensors": "ٹرک ٹیلی میٹری اور سینسرز",
  "Remaining Run": "باقی سفر",
  "Dispatch Operations Radio": "ڈسپیچ آپریشنز ریڈیو",
  "Connected": "منسلک",
  "Central Dispatch": "مرکزی ڈسپیچ",
  "Maintain 85 km/h cruise, road is clear ahead.": "۸۵ کلومیٹر فی گھنٹہ رفتار رکھیں، سڑک صاف ہے۔",
  "You (Driver)": "آپ (ڈرائیور)",
  "Copy that, passing Zalim oasis now.": "سمجھ گیا، ظلم نخلستان سے گزر رہا ہوں۔",
  "Message operations...": "آپریشنز کو پیغام لکھیں...",
  "Welcome, Captain Fahad Al-Qahtani": "خوش آمدید، کپتان فہد القحطانی",
  "Active Duty": "ڈیوٹی پر",
  "Emergency Hotline": "ہنگامی ہاٹ لائن",
  "Calling Dispatch...": "ڈسپیچ کو کال کی جا رہی ہے...",
  "Assigned Truck: Mercedes-Benz Actros L 1863 · Plate: RJD 4821": "مقرر ٹرک: مرسڈیز بینز ایکٹروس L 1863 · پلیٹ: RJD 4821",
  "Message operations": "آپریشنز کو پیغام",
  "Home": "ہوم",
  "Docs": "دستاویزات",
  "Profile": "پروفائل",
  "Geolocation not supported on this device": "اس ڈیوائس پر مقام کی سہولت موجود نہیں",
  "GPS permission denied": "جی پی ایس کی اجازت نہیں دی گئی",

  /* Smart telemetry, fuel & speed */
  "L": "لیٹر",
  "Low fuel": "کم ایندھن",
  "Moderate": "معتدل",
  "Over limit": "حد سے زیادہ",
  "Cruising": "معمول کی رفتار",
  "Truck & Payload Live Telemetry": "ٹرک اور سامان کی براہ راست ٹیلی میٹری",
  "Fuel Tank Level": "ایندھن کا ٹینک",
  "Range ~": "تخمینہ فاصلہ ~",
  "Current Volume: ": "موجودہ مقدار: ",
  "Full Tank State": "مکمل ایندھن",
  "Adequate Fuel": "مناسب ایندھن",
  "Refuel Suggested": "ایندھن کی ضرورت",
  "Live Speedometer": "گاڑی کا سپیڈومیٹر",
  "Highway limit: 90 km/h": "قانونی حد: 90 کلومیٹر",
  "Vehicle Parked": "گاڑی پارک ہے",
  "Speed Exceeded": "حد سے زیادہ رفتار",
  "Cruising Smoothly": "معمول کی رفتار",
  "Safety Limit: 90": "حفاظتی حد: 90",
  "Axle Load: Steer 34% · Tandem 66%": "محوروں پر وزن: اگلا ۳۴% · پچھلا ۶۶%",
  "CG Center of Gravity: Optimal": "مرکز ثقل: متوازن اور مثالی",
  "TPMS: 110 PSI All 4 Axles Verified": "ٹائر پریشر: 110 PSI تمام ۴ ایکسل درست",
  "5G High-Speed Telemetry Link": "5G تیز رفتار ٹیلی میٹری لنک فعال",
  "Smart Fuel Telemetry": "ایندھن کا سمارٹ ٹینک اور ٹیلی میٹری",
  "LIVE": "براہ راست",
  "Est. Range ~ ": "تخمینہ فاصلہ ~ ",
  "Ultrasonic Sensor Active": "الٹراسونک سینسر فعال",
  "Toggle view mode": "پیمائش کا یونٹ تبدیل کریں",
  "Consumption": "ایندھن کھپت",
  "Tank Temp": "ٹینک درجہ حرارت",
  "Fuel Spec": "ایندھن معیار",
  "Tank Volume: ": "ٹینک کی مقدار: ",
  "Optimal Level · Long Haul Ready": "مثالی سطح · لمبے سفر کے لیے تیار",
  "Operational · Adequate Range": "عملی سطح · مناسب فاصلہ",
  "Low Level · Refuel Recommended": "کم سطح · ایندھن بھرنے کی سفارش",
  "Digital Cockpit Speedometer": "ڈیجیٹل کاک پٹ سپیڈومیٹر",
  "ALERT": "انتباہ",
  "RADAR ON": "رڈار آن",
  "PARKED": "پارک شدہ",
  "GPS Calibrated": "جی پی ایس کیلیبریٹڈ",
  "Engine RPM": "انجن آر پی ایم",
  "Active Gear": "فعال گیئر",
  "Eco Efficiency": "ماحول دوست کارکردگی",
  "Safety Threshold: 90": "حفاظتی حد: 90",
  "Live Payload": "براہ راست لوڈ",
  "Tonnage distribution by trailer type": "ٹریلر کی قسم کے لحاظ سے ٹن کا پھیلاؤ",
  "Shipment count by trailer type": "ٹریلر کے لحاظ سے ٹرپس کی تعداد",
  "Tonnage": "وزن",
  "Highest Capacity Segment:": "سب سے زیادہ گنجائش:",
  "Fleet Total:": "کل بیڑا:",
  "Telemetry Active": "براہ راست نگرانی",
  "Status:": "حالت:",
  "Click to focus": "فوکس کرنے کے لیے کلک کریں",
  "Avg": "اوسط",
  "Top Active Trip:": "بہترین فعال ٹرپ:",
  "Fleet Average:": "بیڑے کی اوسط:",
  "Active Visible:": "دستیاب ٹرپس:",
};
